"""Source and exact-mathematics checks for native Calculus bridge batch 2.

These focused checks complement the actual browser generator/grader tests. They
are not a replacement for the official native loader, exporter, or full suite.
"""
from __future__ import annotations
import ast
import base64
import hashlib
import itertools
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET
import yaml
import sympy as sp

ROOT=Path(__file__).resolve().parents[1]
IDS=['MATH_FUNC_006','MATH_FUNC_007','MATH_CALC_001','MATH_CALC_002']
DATA=json.loads((ROOT/'docs/curriculum-data.json').read_text(encoding='utf-8'))

class UniqueLoader(yaml.SafeLoader):
    def construct_mapping(self,node,deep=False):
        self.flatten_mapping(node);result={}
        for k,v in node.value:
            key=self.construct_object(k,deep=deep)
            if key in result:raise ValueError(f'Duplicate YAML key: {key}')
            result[key]=self.construct_object(v,deep=deep)
        return result

def sources():
    folder=ROOT/'content/math/algebra_foundations/skills'
    return [yaml.load(next(folder.glob(id+'_*.yaml')).read_text(encoding='utf-8'),Loader=UniqueLoader) for id in IDS]

def test_native_source_and_review_preview_agree():
    by_id={s['id']:s for s in DATA['skills']}
    for source in sources():
        assert str(source['schema_version'])=='0.2'
        built=by_id[source['id']]
        for key,value in source.items():
            if key not in ('test','schema_version'):assert value==built[key],(source['id'],key)
        assert source['test']['question_count']==built['question_count']==(21 if source['id'] in {'MATH_FUNC_004','MATH_FUNC_007','MATH_CALC_001','MATH_CALC_002'} else 20)
        assert source['test']['randomize_order'] is built['native_randomize_order'] is True
        assert source['test']['questions']==built['native_templates']


def test_metadata_graph_and_taxonomy_are_complete():
    track=yaml.load((ROOT/'content/math/algebra_foundations/track.yaml').read_text(),Loader=UniqueLoader)
    assert len(track['skills'])==len(set(track['skills']))==113
    assert set(IDS)<=set(track['skills'])
    assert set(track['entry_skills']+track['exit_skills'])<=set(track['skills'])
    assert 'MATH_CALC_002' in track['exit_skills']
    all_skills={s['id']:s for s in DATA['skills']}
    assert len(all_skills)==116
    active=set();done=set()
    def visit(id):
        assert id in all_skills,id
        assert id not in active,f'Cycle at {id}'
        if id in done:return
        active.add(id)
        for p in all_skills[id]['prerequisites']:visit(p)
        active.remove(id);done.add(id)
    for id in all_skills:visit(id)
    taxonomy=json.loads((ROOT/'docs/learning-taxonomy.json').read_text())
    branches=next(f for f in taxonomy['fields'] if f['id']=='SUBJECT_MATH')['branches']
    assert 'Calculus' in branches
    assert {s['subdomain'] for s in sources()}=={'Algebra','Calculus'}
    generated='// Generated by scripts/build_learning_taxonomy.py. Edit learning-taxonomy.json.\nexport const FIELD_TAXONOMY = '+json.dumps(taxonomy,ensure_ascii=False,indent=2)+';\n'
    assert (ROOT/'docs/learning-taxonomy.js').read_text()==generated


def test_teaching_coverage_and_review_requirements():
    templates=[]
    for s in sources():
        assert len(s['theory'].split())>=750
        assert len(s['examples'])==10 and len(s['applications'])==4
        assert len([q for q in s['test']['questions'] if not q.get('proof_spec')])==20
        assert s['mastery']['passing_score']==.8
        assert s['mastery']['max_guessing_allowed']=='maybe'
        gates=0
        for q in s['test']['questions']:
            if q.get('proof_spec'): continue
            templates.append(q)
            assert q['explanation_template'].strip() and q['mistake_tags']
            assert q['answer'] and q['grading']
            if q.get('media'):assert q['type']=='fixed' and not q['variables']
            if q['review_policy']['mastery_requires_review_pass']:
                gates+=1
                assert q['answer_mode']=='final_plus_required_work'
                assert q['review_policy']['work_review']=='tutor_required'
                assert q['review_policy']['allow_self_review'] is False
                assert len(q['work']['proof_policy']['obligations'])==4
            if q['work'].get('mode')=='procedural_steps' and q['answer']['type']=='numeric':
                assert 'target_variable' not in q['work'],'Numeric calculation must not demand a dummy x'
        assert gates==1
    assert len({q['id'] for q in templates})==80
    assert sum(q['type']=='generated' for q in templates)==41
    assert sum(q['type']=='fixed' for q in templates)==39


def test_source_placeholders_and_safe_arithmetic_dependencies():
    # Source-level expressions use the intersection of Python and browser native
    # generator features: finite integer draws and simple arithmetic/comparisons.
    allowed=(ast.Expression,ast.BinOp,ast.UnaryOp,ast.Name,ast.Load,ast.Constant,
             ast.Add,ast.Sub,ast.Mult,ast.Div,ast.Pow,ast.USub,ast.UAdd,
             ast.Compare,ast.NotEq,ast.Eq,ast.Lt,ast.LtE,ast.Gt,ast.GtE)
    def strings(v):
        if isinstance(v,str):yield v
        elif isinstance(v,list):
            for item in v:yield from strings(item)
        elif isinstance(v,dict):
            for item in v.values():yield from strings(item)
    for s in sources():
        for q in s['test']['questions']:
            if q.get('proof_spec'): continue
            names=set(q['variables'])
            for name,expr in q['derived'].items():
                tree=ast.parse(expr,mode='eval')
                assert all(isinstance(n,allowed) for n in ast.walk(tree)),q['id']
                assert {n.id for n in ast.walk(tree) if isinstance(n,ast.Name)}<=names
                names.add(name)
            for expr in q['constraints']:
                tree=ast.parse(expr,mode='eval')
                assert all(isinstance(n,allowed) for n in ast.walk(tree))
                assert {n.id for n in ast.walk(tree) if isinstance(n,ast.Name)}<=names
            for text in strings({k:q[k] for k in ['prompt_template','answer','explanation_template','work','options']}):
                for placeholder in re.findall(r'\{([^{}]+)\}',text):
                    assert placeholder in names,(q['id'],placeholder)


def test_exact_difference_quotient_and_secant_identities():
    x,h,a,b,p,q,r=sp.symbols('x h a b p q r')
    f=lambda z:p*z*z+q*z+r
    assert sp.cancel((f(x+h)-f(x))/h-(2*p*x+p*h+q))==0
    assert sp.cancel((f(a+h)-f(a))/h-(2*p*a+p*h+q))==0
    assert sp.cancel(((x+h)**3-x**3)/h-(3*x*x+3*x*h+h*h))==0
    assert sp.cancel((1/(a+h)-1/a)/h+1/(a*(a+h)))==0
    assert sp.cancel((f(b)-f(a))/(b-a)-(p*(a+b)+q))==0
    assert sp.expand(a*a+(a+b)*(x-a)-((a+b)*x-a*b))==0
    # Correct identities do not restore the excluded quotient denominator h=0.
    assert h in sp.fraction((f(x+h)-f(x))/h)[1].free_symbols


def test_exact_limit_and_continuity_parameter_families():
    x=sp.symbols('x',real=True)
    for a in range(-5,6):
        if a:
            assert sp.limit((x*x-a*a)/(x-a),x,a)==2*a
        for m,b in itertools.product(range(1,5),range(-4,5)):
            k=m*a+b-a
            assert m*a+b==a+k
            assert sp.limit((x-a)*(m*x+b)/(x-a),x,a)==m*a+b
    for r in range(1,7):
        assert sp.limit((sp.sqrt(x)-r)/(x-r*r),x,r*r)==sp.Rational(1,2*r)
    for a in range(2,8):
        n=a*a+a;mid=sp.Rational(2*a+1,2)
        assert a*a-n<0 and mid*mid-n==sp.Rational(1,4)
        assert (a+1)**2-n>0
    assert sp.limit(1/x,x,0,dir='+')==sp.oo
    assert sp.limit(1/x,x,0,dir='-')==-sp.oo
    for side in ('+','-'):assert sp.limit(1/x**2,x,0,dir=side)==sp.oo


def test_piecewise_candidate_filtering_and_counterexamples():
    for r,s in itertools.product(range(1,6),repeat=2):
        target=r*r;b=target-s
        candidates=[x for x in (-r,r) if x<0]+[x for x in (target-b,) if x>=0]
        assert set(candidates)=={-r,s}
    # Test the mathematical reasons behind the fixed conceptual counterexamples.
    assert (-2)**2==2**2 and 0**2!=2**2  # Zero average does not imply constant.
    assert {x for x in (-1,0,1) if x**3-x==0}=={-1,0,1}
    assert (-1)**2==1**2==1 and 0**2==0  # Same signs need not exclude a root.
    assert ((2-2)**2-4)==-4             # The position turning point is included.
    assert (abs(-4-0)+abs(0-(-4)))/4==2


def test_new_media_integrity_and_reference_coverage():
    assets=[a for a in DATA['assets'] if a['path'].startswith('media/native-calculus-bridge/')]
    assert len(assets)==12
    assert sum(a['bytes'] for a in DATA['assets'])<1_000_000
    used=set()
    for s in sources():
        for row in [s,*s['examples'],*s['applications'],*s['test']['questions']]:
            for m in row.get('media',[]):
                assert m['alt'] and m['caption'] and m['fit']=='contain'
                assert m['width']==800 and m['height']==500
                used.add(m['src'])
    assert used=={a['path'] for a in assets}
    # Teaching conclusions belong after the assessment, not in test captions.
    teaching_captions={m['caption'] for lesson in sources()
                       for row in [lesson,*lesson['examples'],*lesson['applications']]
                       for m in row.get('media',[])}
    for lesson in sources():
        for question in lesson['test']['questions']:
            for media in question.get('media',[]):
                assert media['caption'] not in teaching_captions
                assert 'guarantees a zero' not in media['caption'].lower()
                assert 'limit is 2' not in media['caption'].lower()
    # The nearby-rate teaching picture has different h values from this question.
    nearby=next(q for lesson in sources() for q in lesson['test']['questions']
                if q['id']=='BRIDGE_RATE_NEARBY')
    assert not nearby.get('media')
    for a in assets:
        raw=(ROOT/'content/math/algebra_foundations/skills'/a['path']).read_bytes()
        assert len(raw)==a['bytes'] and hashlib.sha256(raw).hexdigest()==a['sha256']
        assert base64.b64decode(a['data_base64'])==raw
        root=ET.fromstring(raw)
        assert root.tag.endswith('svg')
        assert b'<script' not in raw.lower() and b'<foreignobject' not in raw.lower()
        # Figures used for testing show givens, not the assessed conclusion.
        for leaked_conclusion in (b'Nearby values approach 2', b'Left limit = 1',
                                   b'Right limit = 3', b'A corner can still be continuous',
                                   b'At least one zero', b'the new value k = 4'):
            assert leaked_conclusion not in raw
        if a['path'].endswith('piecewise-absolute.svg'):
            assert b'3 - x for x' not in raw
