"""Generate the browser module from the machine-readable branch standard."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build():
    taxonomy = json.loads((ROOT / "docs/learning-taxonomy.json").read_text(encoding="utf-8"))
    output = "// Generated by scripts/build_learning_taxonomy.py. Edit learning-taxonomy.json.\n"
    output += "export const FIELD_TAXONOMY = " + json.dumps(taxonomy, ensure_ascii=False, indent=2) + ";\n"
    (ROOT / "docs/learning-taxonomy.js").write_text(output, encoding="utf-8")


if __name__ == "__main__":
    build()
