"""Build MATH_ARITH_010: rounding, significant figures, exactness and bounds."""
from native_number_foundations_common import *

theory = '''Rounding replaces a value by a nearby value at a stated place. It is useful when a measurement, report, or decision does not need every recorded digit, but it changes the value. An exact value is specified without approximation in the problem’s number system, such as 3/8 or exactly 0.375 kg. A measured value may be recorded as 12.4 cm because the instrument resolves tenths; it is a report of a quantity with limited precision, not a claim that all later digits are zero.

To round to a place, keep the digits through that place and inspect the first discarded digit. If it is 0, 1, 2, 3, or 4, keep the retained digit. If it is 5, 6, 7, 8, or 9, increase the retained digit by one. Discarded digits then become zeros in whole-number places or disappear after the decimal point. For 6,347 rounded to the nearest hundred, inspect the tens digit 4 and report 6,300. For 6,350, the tens digit is 5, so report 6,400. State the place; “6,4” is not an adequate answer to a nearest-hundred question.

Rounding can carry into a new place. Rounding 9.96 to the nearest tenth starts with retained digit 9 and a discarded hundredths digit 6. Increasing 9 tenths produces 10 tenths, which is 1 whole, so the answer is 10.0. Keep a trailing zero when it communicates the requested place. A negative number is rounded by distance to the target multiples; if signed values arise, decide using the same nearest-value idea rather than treating a minus sign as a digit.

Significant figures record meaningful digits in a measurement. Nonzero digits always count. Zeros between nonzero digits count, as in 1002 (four significant figures). Leading zeros only locate the decimal point and do not count, as in 0.00450 (three significant figures: 4, 5, and the final zero). Trailing zeros after a decimal point count, as in 2.300 (four significant figures). A whole number such as 1500 is ambiguous without notation; write 1.5×10^3 for two significant figures or 1.500×10^3 for four. Scientific notation makes the intended precision visible.

For multiplication and division, a common reporting rule is to give the result to the fewest significant figures among the measured inputs. For addition and subtraction, compare decimal places instead: align the values and report to the least precise decimal place. These rules describe a sensible measurement report; they do not make the intermediate arithmetic less exact. Keep extra guard digits during calculation, then round once at the end. Exact counted numbers, defined constants, and specified conversions do not limit significant figures in the same way as measured inputs.

Bounds make an approximation informative. If a value x rounds to 48.4 to the nearest tenth, then 48.35 ≤ x < 48.45. The lower endpoint is included because 48.35 is exactly halfway and rounds up under the usual half-up convention; the upper endpoint is excluded because 48.45 would round to 48.5. For rounding to the nearest whole number n, the interval is [n−0.5,n+0.5). If a displayed value is truncated rather than rounded, its bounds differ: 48.4 truncated to one decimal means 48.4 ≤ x < 48.5.

Use a symbol or inequality for uncertainty instead of inventing digits. A mass reported as 2.30 g to the nearest hundredth lies from 2.295 g up to but not including 2.305 g. A calculation using bounds can estimate a range for an area or cost, but the result’s precision should not imply more knowledge than the inputs provide. Do not confuse accuracy (closeness to a true value) with precision (repeatable detail or resolution); rounding changes the reported precision, while calibration affects accuracy.

Before rounding, identify the target place or number of significant figures. Mark the last kept digit, inspect the next digit, and perform any carry. Afterward, check that the notation still communicates the requested precision and that the result is close to the original. The capstone asks you to give a rounded measurement and its half-open bounds, and to explain why the upper endpoint is excluded.
Rounding is a communication decision as well as a calculation. A bus timetable may round a duration to the nearest minute, while a laboratory report may retain hundredths because the instrument supports them. The same underlying value can therefore have several honest displays, provided each display states its place or significant-figure rule. When comparing rounded values, remember that two displays can overlap in their possible true intervals; a visible difference does not always prove the underlying values differ.

A bound is an interval statement, so endpoint symbols carry information. For nearest-tenth half-up rounding, the lower midpoint belongs to the displayed bin and the upper midpoint belongs to the next bin. If a problem uses a different tie rule, such as ties-to-even, state that rule before changing the endpoint. Bounds are also useful in later calculations: adding lower bounds gives a lower bound for a sum when all quantities are nonnegative, while multiplying bounds requires attention to signs. Keep the simple one-value interval separate from those later interval operations.
'''

examples = [
    example('Round 6,347 to the nearest hundred.', '6,300', 'The tens digit is 4, so keep the hundreds digit and replace later places by zero.'),
    example('Round 6,350 to the nearest hundred.', '6,400', 'The tens digit is 5, so increase the hundreds digit.'),
    example('Round 9.96 to the nearest tenth.', '10.0', 'The hundredths digit 6 raises 9 tenths to 10 tenths, which is 10.0.'),
    example('How many significant figures are in 0.00450?', '3', 'Leading zeros do not count; 4, 5, and the trailing decimal zero do.'),
    example('Write 1500 to two significant figures in scientific notation.', '1.5×10^3', 'Scientific notation makes the two meaningful digits explicit.'),
    example('Round 12.347 to three decimal places.', '12.347', 'The requested place is already the thousandths place.'),
    example('Round 12.347 to two decimal places.', '12.35', 'The third decimal digit is 7, so the hundredths digit increases.'),
    example('Give bounds for a value rounding to 8.2 to the nearest tenth.', '8.15 ≤ x < 8.25', 'Half a tenth on either side gives the interval; the upper endpoint would round to 8.3.'),
    example('Which is exact: 12 counted chairs or 12.0 cm measured length?', '12 counted chairs', 'Counting can give an exact whole number; the measurement has instrument precision.'),
    example('Round 0.00996 to two significant figures.', '0.010', 'The significant digits are 9 and 9; carrying produces 1.0×10^-2, written 0.010 to show two figures.'),
]
apps = [
    application('Instrument readings', 'A ruler, scale, or sensor determines a resolution, so rounded reports need a place and meaningful bounds.'),
    application('Budgets and estimates', 'A rounded cost can support a quick decision while bounds show how much the true total could differ.'),
    application('Science reporting', 'Significant figures prevent a calculation from claiming more precision than the measured inputs support.'),
    application('Public data displays', 'Tables and dashboards use rounding to stay readable, but exact source values and rounding rules should remain recoverable.'),
]
questions = [
    fixed('ARITH010_NEAREST_TEN', 'Round 4,376 to the nearest ten.', '4380', 'The ones digit 6 rounds the tens digit up: 4,380.', tags=['rounding', 'place_value']),
    fixed('ARITH010_NEAREST_HUNDRED', 'Round 6,347 to the nearest hundred.', '6300', 'The tens digit is 4, so the hundreds digit stays 3.', tags=['rounding']),
    fixed('ARITH010_HALF_UP', 'Round 6,350 to the nearest hundred.', '6400', 'A discarded 5 rounds the kept hundreds digit up.', tags=['rounding', 'tie_rule']),
    fixed('ARITH010_CARRY', 'Round 9.96 to the nearest tenth.', '10.0', '6 hundredths raises 9 tenths to 10 tenths; retain the requested tenth place.', tags=['rounding', 'carry']),
    fixed('ARITH010_DECIMAL_PLACES', 'Round 12.347 to two decimal places.', '12.35', 'The third decimal digit is 7, so 12.34 rounds upward.', tags=['rounding', 'decimal_places']),
    choice('ARITH010_SIG_ZERO', 'Which statement correctly describes significant figures?', 'A', [('A', '0.00450 has 3, 1002 has 4, and 1.500×10^3 has 4'), ('B', 'Leading zeros always count'), ('C', '1002 has 3 because its zeros are leading'), ('D', '1.500×10^3 has 2 because the exponent counts')], 'Leading zeros do not count; captive and trailing decimal zeros do.', tags=['significant_figures']),
    choice('ARITH010_SIG_MIDDLE', 'Which is correctly rounded to 2 significant figures?', 'A', [('A', '0.0050 from 0.00496'), ('B', '0.005 from 0.00496'), ('C', '0.0049 from 0.00496'), ('D', '0.00496 unchanged')], 'The first two significant digits are 4 and 9; carrying the next 6 gives 0.0050, whose trailing zero communicates two figures.', tags=['significant_figures', 'rounding']),
    choice('ARITH010_SIG_SCI', 'For measured 3.40×2.1, how many significant figures should the product report?', 'B', [('A', '1'), ('B', '2'), ('C', '3'), ('D', '5')], 'Multiplication reports to the fewest significant figures: 2.1 has two.', tags=['significant_figures', 'multiplication']),
    choice('ARITH010_EXACT_COUNT', 'Which statement is correct?', 'A', [('A', 'A count of exactly 12 chairs can be exact'), ('B', 'Every measured value is exact'), ('C', 'Rounding creates an exact value'), ('D', 'An estimate has no reference'),], 'A counted quantity can be exact when the count is stated exactly.', tags=['exactness']),
    choice('ARITH010_MEASURED', 'A length is measured as 12.4 cm to the nearest tenth. Which description fits?', 'B', [('A', 'It is an exact claim that the length is 12.400... cm'), ('B', 'It is an approximate report with bounds'), ('C', 'It has no unit'), ('D', 'It is a count')], 'A nearest-tenth measurement represents an interval of possible true lengths.', tags=['exactness', 'measurement']),
    choice('ARITH010_BOUNDS_TENTH', 'A value rounds to 8.2 to the nearest tenth. Which interval contains the possible exact values?', 'C', [('A', '8.2≤x≤8.3'), ('B', '8.15<x≤8.25'), ('C', '8.15≤x<8.25'), ('D', '8.10≤x<8.20')], 'The lower midpoint is included and the upper midpoint is excluded under half-up rounding.', tags=['bounds']),
    fixed('ARITH010_BOUNDS_UPPER', 'A=2.30±0.05 and B=1.20±0.02. Enter the greatest possible value of A+B.', '3.57', 'Use upper bounds: 2.35+1.22=3.57.', tags=['bounds', 'propagated_measurement']),
    choice('ARITH010_TRUNCATION', 'A value is truncated to 4.2 at one decimal place. Which interval is correct?', 'B', [('A', '4.1≤x<4.2'), ('B', '4.2≤x<4.3'), ('C', '4.15≤x<4.25'), ('D', '4.2<x≤4.3')], 'Truncation keeps 4.2 as the lower endpoint and stops before 4.3.', tags=['bounds', 'truncation']),
    choice('ARITH010_TRUNCATION_UPPER', 'Which estimate/exact pair is correct for 398.6+201.7, estimating to the nearest hundred?', 'D', [('A', 'Estimate 500; exact 600.3'), ('B', 'Estimate 700; exact 600.3'), ('C', 'Estimate 600; exact 599.3'), ('D', 'Estimate 600; exact 600.3')], '398.6≈400 and 201.7≈200, while the unrounded exact sum is 600.3.', tags=['estimation', 'exact_value']),
    choice('ARITH010_ADD_PRECISION', 'For 2.30 + 1.4, which decimal place should a sensible reported answer use?', 'A', [('A', 'Tenths'), ('B', 'Hundredths'), ('C', 'Thousandths'), ('D', 'No decimal place ever')], 'Addition is limited by the least precise input, 1.4, which is to tenths.', tags=['precision', 'addition']),
    fixed('ARITH010_MULT_PRECISION', 'Round 9.949 directly to the nearest tenth, without first rounding it.', '9.9', 'The hundredths digit is 4, so direct rounding gives 9.9. Rounding first to 9.95 would create a different double-rounding result.', tags=['rounding', 'double_rounding']),
    choice('ARITH010_ACCURACY_PRECISION', 'Which statement distinguishes precision from accuracy?', 'A', [('A', 'Precision is repeatable detail; accuracy is closeness to truth'), ('B', 'Precision and accuracy are identical'), ('C', 'Accuracy counts decimal places only'), ('D', 'Precision means the answer is exact')], 'Precision describes resolution or repeatability; accuracy describes closeness to the true value.', tags=['measurement_reasoning']),
    choice('ARITH010_HALF_OPEN', 'For nearest-whole half-up rounding to 5, which interval is correct?', 'C', [('A', '4.5 < x < 5.5'), ('B', '4.5 ≤ x ≤ 5.5'), ('C', '4.5 ≤ x < 5.5'), ('D', '4.0 ≤ x < 5.0')], 'The lower midpoint is included and the upper midpoint belongs to 6.', tags=['bounds', 'rounding']),
    fixed('ARITH010_SCI_PRECISION', 'Rounding 12.34 to the nearest tenth has what maximum absolute error?', '0.05', 'A nearest-tenth report can differ by at most half a tenth, 0.05.', tags=['rounding', 'maximum_error']),
    capstone('ARITH010_CAPSTONE', 'A length is displayed as 48.4 cm after rounding to the nearest tenth. Enter the lower endpoint of the possible exact interval.', '48.35', ['States the lower endpoint 48.35 cm and explains why it is included.', 'Gives the full interval 48.35≤x<48.45 cm and connects it to nearest-tenth rounding.', 'Provides a sensible estimate of the true length and distinguishes the displayed approximation from an exact length.'], 'The display 48.4 cm means 48.35≤x<48.45 cm. A reasonable estimate is 48.4 cm; the lower midpoint is included and the upper midpoint would round to 48.5.'),
]

figure('arith010-rounding-line.svg', 'Rounding 48.37 to the nearest tenth', '<line x1="75" y1="170" x2="730" y2="170" stroke="#287365" stroke-width="4"/><line x1="200" y1="145" x2="200" y2="195" stroke="#287365" stroke-width="4"/><line x1="360" y1="145" x2="360" y2="195" stroke="#287365" stroke-width="4"/><line x1="520" y1="145" x2="520" y2="195" stroke="#287365" stroke-width="4"/><circle cx="200" cy="170" r="10" fill="#287365"/><circle cx="520" cy="170" r="10" fill="#fffdf7" stroke="#287365" stroke-width="4"/><circle cx="264" cy="170" r="11" fill="#d96d4f"/><text x="182" y="225" font-size="19">48.35 included</text><text x="335" y="225" font-size="19">48.4</text><text x="500" y="225" font-size="19">48.45 excluded</text><text x="234" y="135" font-size="19">48.37</text><text x="245" y="285" font-size="21">[48.35, 48.45) → display 48.4</text>')
figure('arith010-significant.svg', 'Significant zeros', '<rect x="45" y="86" width="300" height="92" fill="#d9eee5"/><rect x="455" y="86" width="300" height="92" fill="#f5dfb5"/><text x="195" y="142" text-anchor="middle" font-size="28">0.00450</text><text x="605" y="142" text-anchor="middle" font-size="28">1.500×10⁻²</text><text x="82" y="235" font-size="21">leading zeros locate</text><text x="498" y="235" font-size="21">trailing decimal zero counts</text>')

save('MATH_ARITH_010', 'Rounding, significant figures and bounds', theory, ['MATH_ARITH_009'], examples, apps, questions, [media('arith010-rounding-line.svg', 'A number line marks 48.35 included, 48.37, and 48.45 excluded for a nearest-tenth report of 48.4.', 'Rounding to a tenth describes a half-open interval.'), media('arith010-significant.svg', '0.00450 has three significant figures, while 1.500 times ten to the negative second has four. Leading zeros locate the decimal place; trailing decimal zeros communicate precision.', 'Scientific notation makes significant figures visible.')], tags=['arithmetic', 'rounding', 'significant_figures', 'bounds', 'measurement'])
