"""Build the native direct/inverse proportion lesson and its instructional SVGs."""
from pathlib import Path
import yaml
from build_arithmetic_onramp_core import ex,var,q,cap,media,svg,save
text='''A proportional model describes a particular relationship between quantities. You must identify the quantities, their units, and the conditions under which the model makes sense. A table or graph can suggest a model; an unexplained pattern in a few measurements is not a proof that the model will work everywhere.

Direct proportion means y = kx with one fixed constant k on the stated domain. For x not zero, y/x = k. If each metre of identical ribbon costs 3 currency units and there is no extra fee, 2 metres costs 6 and 5 metres costs 15. Doubling the length doubles the cost. The unit rate is 3 currency units per metre. Zero metres costs zero, so the complete mathematical line goes through the origin. In a context, only nonnegative lengths may make sense even though the formula can accept negative inputs.

Find k by dividing an output by its matching nonzero input, not by dividing two outputs from different rows. If y = 18 when x = 6, then k = 18/6 = 3. Use y = 3x to find another output, or divide y by 3 to recover an input. A ratio table scales both quantities by the same factor. The factor may be a fraction: halving a quantity halves its directly proportional partner. Matching units matters: convert minutes to hours before comparing rates quoted per hour.

A straight line is not automatically direct proportion. A delivery charge y = 3x + 5 is linear, but the fixed fee makes y/x depend on x. For x = 1 the ratio is 8; for x = 2 it is 11/2. The graph does not pass through the origin, and doubling x does not double y. A constant difference between consecutive outputs shows a constant slope when inputs have equal steps; it does not by itself show a constant output-to-input ratio. In contrast, for y = 3x, both the slope and the direct-proportion test agree.

Inverse proportion means y = k/x with a fixed nonzero k on a domain excluding x = 0. The product xy = k remains fixed. If a fixed 24-litre supply is shared equally among x identical containers, each receives y = 24/x litres. Twice as many containers means half as much in each, and three times as many means one third as much. The constant has units of the product: in this example container-count times litres per container gives the fixed number of litres. With x as a positive count, only positive integer inputs are physically possible even if a smooth curve helps show the pattern.

Find an inverse constant by multiplying a matched input and output. If y = 8 when x = 3, then k = 24; y = 24/x gives y = 4 at x = 6. To find x from y, solve xy = k, so x = k/y when y is nonzero. Do not use y/x here: that ratio changes. For positive k and positive inputs, the graph curves down as x grows. It approaches the axes without meeting them. The point x = 0 is excluded, not a hidden value on the vertical axis, and the curve must not be drawn across that gap.

Not every decreasing relationship is inverse proportion. The rule y = 10 - x decreases but its product xy is not fixed: at x = 2 the product is 16, while at x = 3 it is 21. Likewise, not every increasing relationship is direct: y = x squared has ratios x, not one constant. Check the invariant the definition requires. For direct proportion test y/x wherever x is nonzero and include the origin when the domain includes zero. For inverse proportion test xy and exclude zero from the input domain. A single matching pair cannot distinguish the models; both can be made to pass through one nonzero point.

Real situations need assumptions. More workers may shorten a job in inverse proportion only when the amount of work is fixed, workers have equal constant productivity, and they can work independently without delays. Doubling workers need not halve travel time or a task with a single shared machine. A constant-speed journey has distance directly proportional to time, whereas time is inversely proportional to speed for a fixed distance. Naming which quantity is fixed prevents these statements from being confused.

Representations should tell the same story. Use a table to test the ratio or product, an equation to calculate exact values, and a graph to see shape and domain. Axis scales may differ, so the angle a line seems to make on screen is not its numerical slope. The generated graphs in this lesson are drawn from the stated formula and parameters, not from a hidden answer. Explain why you selected a model, state its restrictions, and verify a result in the original relation. The reviewed capstone compares direct proportion, a line with an intercept and inverse proportion; selecting a familiar formula without justification is insufficient.'''
examples=[ex('Ribbon costs 3 units per metre with no fixed charge. Cost of 5 m?','15 units','y=3x; 3 times 5=15. The unit rate is currency per metre.'),ex('y is directly proportional to x; y=18 when x=6. Find k.','3','Divide matching values: k=y/x=18/6. The model is y=3x.'),ex('Use y=3x to find x when y=27.','9','Solve 27=3x. Dividing both sides by3 gives x=9.'),ex('Do pairs (2,6),(4,12),(7,21) fit direct proportion?','Yes, k=3','Each y/x is3; both quantities scale together.'),ex('Is y=3x+5 direct proportion?','No','At x=0 output5 is nonzero; ratios at1 and2 differ. It is linear but not directly proportional.'),ex('A fixed24L is shared across3 containers. Then across6. Amount per container?','8L then4L','xy=24 stays fixed; doubling the count halves the amount per container.'),ex('y is inversely proportional to x; y=8 at x=3. Find y at x=6.','4','k=3 times8=24, so y=24/6=4.'),ex('For y=24/x, find x if y=2.','12','xy=24 gives2x=24. Input zero is never allowed.'),ex('Is y=10-x inverse proportion?','No','At x=2 the product is16; at x=3 it is21. Decreasing alone is not enough.'),ex('Four equal independent workers finish a divisible job in6 hours. Ideal time for8 workers?','3 hours','Under constant equal productivity, worker-hours stay24. Shared bottlenecks would invalidate this model.')]
apps=[ex('At constant60km/h, how far in2.5hours?','150km','Distance=rate times time; no fixed starting-distance offset is included.'),ex('A60km journey is driven at30km/h or60km/h. Compare times.','2h and1h','Distance stays fixed, so speed times time=60 and time is inverse to speed.'),ex('A taxi charges5 units plus2 per kilometre. Is fare proportional to kilometres?','Not directly proportional','The fixed charge causes a nonzero intercept; the fare for twice the distance is less than twice the original fare.'),ex('A printer produces150 pages in5min at a fixed rate. Time for420pages?','14min','Rate=30pages/min. With no setup delay, time=420/30=14min.')]
questions=[]
questions.append(q('PROP_DIRECT_RATE','y is directly proportional to x. At x={x}, y={y}. Find k in y=kx.','{k}','k=y/x for a nonzero paired input.',{'x':var(2,9),'k':var(2,8)},{'y':'k*x'}))
questions.append(q('PROP_DIRECT_OUTPUT','For y={k}x, find y when x={x}.','{y}','Multiply the input by the stated unit rate.',{'k':var(2,6),'x':var(2,9)},{'y':'k*x'}))
questions.append(q('PROP_DIRECT_INPUT','For y={k}x, find x when y={y}.','{x}','Divide the output by the nonzero constant.',{'k':var(2,8),'x':var(2,9)},{'y':'k*x'}))
questions.append(q('PROP_DIRECT_FRACTION','For y=x/{d}, find y at x={x}.','{n}/{d}','A fractional unit rate still defines direct proportion.',{'d':var(2,5),'n':var(3,9)},{'x':'n'}))
questions.append(q('PROP_DIRECT_SCALE','Directly proportional quantities have y={y} at x={x}. Find y at x={newx}.','{ans}','Both inputs and outputs scale by {factor}.',{'x':var(2,5),'y':var(3,9),'factor':var(2,5)},{'newx':'x*factor','ans':'y*factor'}))
questions.append(q('PROP_DIRECT_ZERO','A direct-proportion model includes x=0. What must y be there?','0','y=k times0=0. This distinguishes a nonzero-intercept line.'))
questions.append(q('PROP_INTERCEPT','Which formula is direct proportion?','B','Only y=4x has a fixed y/x and passes through the origin.',choices=['y=4x+3','y=4x','y=4/x','y=x^2']))
questions.append(q('PROP_TABLE','Pairs (1,5),(2,8),(3,11) have equal output differences. Are they directly proportional?','C','The differences are3, but y/x is5,4,11/3. The intercept is2.',choices=['Yes because they form a line','Yes because y increases','No because y/x changes','No because direct proportion decreases']))
questions.append(q('PROP_INVERSE_CONSTANT','y is inversely proportional to x. At x={x}, y={y}. Find k in y=k/x.','{k}','Multiply matching values to find the fixed product.',{'x':var(2,9),'y':var(2,9)},{'k':'x*y'}))
questions.append(q('PROP_INVERSE_OUTPUT','For y={k}/x, find y at x={x}.','{y}','Divide the fixed product by the input.',{'x':var(2,9),'y':var(2,9)},{'k':'x*y'}))
questions.append(q('PROP_INVERSE_INPUT','For y={k}/x, find x when y={y}.','{x}','xy={k}, so divide by the stated nonzero output.',{'x':var(2,9),'y':var(2,9)},{'k':'x*y'}))
questions.append(q('PROP_INVERSE_SCALE','For inverse proportion, y={y} at x={x}. Find y at x={newx}.','{base}','Multiplying the input by {f} divides its inverse partner by {f}.',{'x':var(2,6),'base':var(2,6),'f':var(2,5)},{'y':'base*f','newx':'x*f'}))
questions.append(q('PROP_INVERSE_DOMAIN','Why is x=0 excluded from y=24/x?','A','Division by zero is undefined, and 0 times y cannot equal24.',choices=['No value of y makes 0 times y equal24','The answer is secretly zero','The graph merely hides a value','Only negative inputs are forbidden']))
questions.append(q('PROP_DECREASE','Which check proves that y=10-x is not inverse proportion on positive inputs?','B','Inverse proportion requires a fixed product, not simply decreasing outputs.',choices=['It decreases','At x=2 and3, xy is16 and21','It has two variables','It can be drawn']))
questions.append(q('PROP_UNITS','At {rate} km/h, a journey lasts {minutes} minutes. How many km are travelled?','{distance}','Convert minutes to hours, then multiply by speed.',{'r':var(2,8),'m':var(1,5)},{'rate':'12*r','minutes':'5*m','distance':'r*m'}))
questions.append(q('PROP_FIXED_DISTANCE','A fixed {distance} km journey is driven at {speed} km/h. Time in hours?','{hours}','Time=distance/speed; distance is the fixed quantity.',{'hours':var(2,6),'speed':var(20,60)},{'distance':'hours*speed'}))
questions.append(q('PROP_WORKERS','With equal constant independent productivity, {a} workers take {t} hours. How many hours for {b} workers on the same divisible job?','{ans}','Keep worker-hours fixed; the extra assumption of independent work matters.',{'a':var(2,5),'ans':var(2,6),'f':var(2,4)},{'t':'ans*f','b':'a*f'}))
questions.append(q('PROP_ASSUMPTION','When is time inversely proportional to worker count for a fixed job?','C','The model requires equal constant rates and work that can be divided without bottlenecks.',choices=['For every job regardless of conditions','Whenever time decreases at all','With equal constant productivity and independent divisible work','Only when the number of workers is zero']))
questions.append(q('PROP_GRAPH','The graph shows the stated model y={k}/x for positive x. If x changes from 2 to 4, what happens to y?','B','The fixed product stays {k}; doubling x halves y.',{'k':var(4,12)},choices=['It doubles','It halves','It decreases by exactly2 for every k','It stays fixed']))
questions[-1]['diagram']=dict(kind='cartesian',x_range=[0,8],y_range=[0,14],alt='The stated positive-input curve y={k}/x; zero input is excluded.',curves=[dict(expression='{k}/x',interval=[0.5,8],endpoints=['none','none'])])
questions[1]['diagram']=dict(kind='cartesian',x_range=[0,10],y_range=[0,60],alt='The given direct-proportion line y={k}x for nonnegative inputs.',curves=[dict(expression='{k}*x',interval=[0,10])])
questions.append(cap('PROP_CAPSTONE','Model A is y=3x; B is y=3x+5; C is y=24/x for x>0. How many are directly proportional? Enter the count, then justify each classification using ratio or product, explain the intercept test, and state C\'s input restriction.','1','A has y/x=3; B has a nonzero intercept and changing y/x; C has xy=24 and excludes zero. Only A is direct.',['Shows A has fixed ratio and zero intercept.','Rejects B using its varying ratio or nonzero intercept, despite its straight graph.','Identifies C as inverse with fixed product and explicitly excludes zero.']))
# Exact-coordinate instructional plots; the assessment diagrams remain parameter-linked.
axes=''
for ox in [65,450]:
 axes+=f'<path d="M{ox} 75V270H{ox+280}" fill="none" stroke="#163f36" stroke-width="2"/><text x="{ox+10}" y="70" font-size="18">y</text><text x="{ox+284}" y="279" font-size="18">x</text><text x="{ox-17}" y="288" font-size="16">0</text>'
for x in [1,2,3,4]:
 px=65+x*65;axes+=f'<path d="M{px} 270v5" stroke="#163f36"/><text x="{px}" y="291" text-anchor="middle" font-size="15">{x}</text>'
for y in [6,12,18]:
 py=270-y*10;axes+=f'<text x="58" y="{py+5}" text-anchor="end" font-size="15">{y}</text>'
for x in [2,4,6,8]:
 px=450+x*32.5;axes+=f'<path d="M{px} 270v5" stroke="#163f36"/><text x="{px}" y="291" text-anchor="middle" font-size="15">{x}</text>'
for y in [4,8,12,16]:
 py=270-y*11;axes+=f'<text x="443" y="{py+5}" text-anchor="end" font-size="15">{y}</text>'
curve=' '.join(f'{450+x*32.5:.2f},{270-24/x*11:.2f}' for x in [1.5+i*6.5/100 for i in range(101)])
svg('proportion-contrast','Three patterns: test the right invariant',axes+f'<path d="M65 270L325 150" stroke="#287365" stroke-width="4"/><path d="M65 220L325 100" stroke="#b25032" stroke-dasharray="7 5" stroke-width="3"/><polyline points="{curve}" fill="none" stroke="#287365" stroke-width="4"/><text x="75" y="313" font-size="17">Solid: y = 3x; dashed: y = 3x + 5</text><text x="455" y="313" font-size="17">y = 24/x; x &gt; 0; xy = 24</text><text x="32" y="344" font-size="16">Direct proportion passes through the origin. A decreasing curve alone does not prove inverse proportion.</text>')
save('MATH_ALG_009','Direct and inverse proportion',text,['MATH_ARITH_011','MATH_FUNC_001','MATH_ALG_001'],examples,apps,questions,[media('proportion-contrast','The line y=3x passes through the origin; y=3x+5 has intercept5. The positive curve y=24/x has fixed product24.','A constant difference, constant ratio and constant product are different claims.')])
p=next((Path(__file__).resolve().parents[1]/'content/math/algebra_foundations/skills').glob('MATH_ALG_009_*.yaml'));data=yaml.safe_load(p.read_text());data['subdomain']='Algebra';data['topic']='Proportional reasoning';data['tags']=['algebra','proportion','unit_rates','model_assumptions'];p.write_text(yaml.safe_dump(data,sort_keys=False,allow_unicode=True,width=105),encoding='utf-8')
