"""Build MATH_ARITH_007: factors, multiples, primes, GCF and LCM."""
from native_number_foundations_common import *

theory = '''Factors and multiples describe how whole numbers are built and repeated. A factor of n is a whole number that divides n with no remainder. If 4 times 9 = 36, then 4 and 9 are factors of 36, while 36 is a multiple of both 4 and 9. The word factor names the parts of a product; multiple names a result in a skip-counting sequence. Zero is a multiple of every whole number because 0 times k = 0, but zero is not a factor of any number because division by zero is undefined.

To list factors, test whole numbers in pairs. For 36, start at 1: 1 times 36, 2 times 18, 3 times 12, and 4 times 9. Once the smaller factor passes the square root, the pairs repeat in reverse, so the complete positive list is 1, 2, 3, 4, 6, 9, 12, 18, 36. A factor-pair check is safer than guessing divisors: every claimed factor must multiply by its partner to make the target, and no pair should be counted twice. A square number such as 49 has a middle pair 7 times 7, so that factor appears once in the list even though it supplies both positions in the pair.

Prime numbers have exactly two positive factors, 1 and themselves. The number 2 is the only even prime. One is neither prime nor composite because it has only one positive factor. A composite number has at least one additional factor; 15 has 1, 3, 5, and 15. To test whether a number n is prime, try divisors up to the square root of n. If none divides evenly, no larger factor can appear without a smaller partner already found. This makes a short, reasoned test instead of a long list of guesses. Divisibility shortcuts help: a number divisible by 2 is even; one ending in 0 or 5 is divisible by 5; a number whose digit sum is divisible by 3 is divisible by 3.

Prime factorization writes a composite number as a product of primes. Factor 84 by splitting 84 = 2 times 42, then 42 = 2 times 21, and 21 = 3 times 7. Thus 84 = 2 times 2 times 3 times 7, or 2 squared times 3 times 7. The order of factors does not matter, but every factor must be prime at the end. A factor tree is a record of choices, not a different answer: splitting 84 as 6 times 14 eventually gives the same multiset of prime factors. Multiplying the primes back together checks the factorization.

The greatest common factor (GCF) of two or more numbers is the largest positive factor they share. For 24 and 36, the common factors include 1, 2, 3, 4, 6, and 12, so the GCF is 12. A factor-list method is transparent for small numbers. A prime-factor method is efficient for larger numbers: write each number in primes, keep only primes that appear in every number, and use the smallest exponent. The GCF is useful for making equal groups as large as possible or simplifying a fraction without changing its value.

The least common multiple (LCM) is the smallest positive number that belongs to both multiple lists. Multiples of 6 are 6, 12, 18, 24, 30; multiples of 8 are 8, 16, 24, so the LCM is 24. With prime factors, keep every prime using the largest exponent appearing in any number. For 12 = 2 squared times 3 and 18 = 2 times 3 squared, the LCM is 2 squared times 3 squared = 36. The LCM answers repeat-together questions; the GCF answers shared-building questions. They can be linked by GCF(a,b) times LCM(a,b) = a times b for positive a and b, which is a useful check rather than a replacement for understanding.

Read the context before choosing GCF or LCM. If 48 red beads and 60 blue beads must be split into identical bags with no leftovers, the greatest possible number of bags is GCF(48,60) = 12. If a red light flashes every 8 seconds and a blue light every 12 seconds and both flash now, the next simultaneous flash is after LCM(8,12) = 24 seconds. For a factor question, ask “what equal groups fit exactly?” For a multiple question, ask “when does this repeated step land?” A number can be a factor of one target and a multiple of another; the roles depend on the sentence.

Explain your method with a product, list, or prime record. Do not call 1 prime, stop a factor tree with a composite leaf, or choose a large common factor that is not actually common. The capstone asks you to model a repeated schedule and justify why the first shared time is the least common multiple.'''

examples = [
    example('List the positive factor pairs of 36.', '1×36, 2×18, 3×12, 4×9, 6×6', 'Each pair multiplies to 36; after 6×6, the pairs reverse.'),
    example('Is 29 prime or composite?', 'Prime', 'Only 1 and 29 divide it; testing primes through √29 is enough.'),
    example('Write 84 as a product of prime factors.', '2×2×3×7', 'Split 84 into 2×42 and 42 into 2×3×7; every final factor is prime.'),
    example('Find the GCF of 24 and 36.', '12', 'The shared factors end at 12, or keep 2²×3 from both prime factorizations.'),
    example('Find the LCM of 6 and 8.', '24', '24 is the first number in both multiple lists.'),
    example('Why is 1 neither prime nor composite?', 'It has exactly one positive factor.', 'Prime requires exactly two positive factors; composite requires more than two.'),
    example('What is the first positive multiple of every whole number?', 'The number itself', 'For positive k, 1×k=k, and no positive multiple is smaller.'),
    example('Use divisibility to decide whether 735 is divisible by 3.', 'Yes', '7+3+5=15, and 15 is divisible by 3.'),
    example('What is the GCF useful for when making equal groups?', 'The largest possible group count or shared size, depending on what is being grouped.', 'Translate the nouns: GCF captures the greatest exact sharing structure.'),
    example('Two bells ring every 9 and 15 minutes. When do they ring together again?', '45 minutes', 'The first shared positive multiple is LCM(9,15)=45.'),
]
apps = [
    application('Packing equal kits', 'A coordinator uses a GCF to make the largest number of identical kits from several inventories without leftovers.'),
    application('Repeating signals', 'Traffic lights, alarms, and machine cycles use LCM reasoning to predict the next simultaneous event.'),
    application('Tiling and arrays', 'Factor pairs describe the possible rectangular rows and columns of a fixed collection of tiles.'),
    application('Fraction simplification', 'The GCF removes a common factor from numerator and denominator while preserving the represented quantity.'),
]

v = lambda lo, hi: {"type": "int", "min": lo, "max": hi}
questions = [
    generated('ARITH007_PRODUCT_FACTOR', 'A tray has {p} rows of {q} markers. How many markers are on the tray?', {'p': v(3, 9), 'q': v(4, 8)}, {'total': 'p*q'}, '{total}', 'Multiply rows by markers per row; the result is the requested total count.', tags=['factors', 'multiplication']),
    fixed('ARITH007_FACTOR_LIST', 'Enter the greatest positive factor of 48 that is less than 48.', '24', 'Factor pairs 1×48, 2×24, 3×16, 4×12, 6×8 show that 24 is the largest proper factor.', tags=['factor_pairs']),
    choice('ARITH007_PRIME_TEST', 'Classify 91.', 'B', [('A', 'Prime'), ('B', 'Composite'), ('C', 'Neither prime nor composite')], '91=7×13, so it has more than two positive factors.', tags=['prime_test']),
    generated('ARITH007_PRIME_DIGIT_SUM', 'A number has digits 4, {a}, and 5. Enter its remainder when divided by 3.', {'a': v(0, 9)}, {'n': '4*100+a*10+5', 'digit_sum': '9+a', 'remainder': '(9+a)%3'}, '{remainder}', 'The digit sum is 9+{a}; its remainder modulo 3 is the requested remainder.', tags=['divisibility', 'digit_sum']),
    fixed('ARITH007_ONE_STATUS', 'Enter 1 if 1 is prime, or 0 if it is not prime.', '0', 'One has exactly one positive factor, so it is neither prime nor composite.', tags=['prime_definition']),
    choice('ARITH007_PRIME_FACTOR_POWER', 'Which is the complete prime factorization of 84?', 'B', [('A', '2×42'), ('B', '2×2×3×7'), ('C', '4×3×7'), ('D', '2×2×21')], 'Only option B has prime factors all the way to the leaves; multiplying them gives 84.', tags=['prime_factorization']),
    fixed('ARITH007_GCF_LIST', 'How many positive common factors do 24 and 36 have?', '6', 'The common factors are 1, 2, 3, 4, 6, and 12, so there are six.', tags=['gcf', 'factor_lists']),
    choice('ARITH007_GCF_COMMON', 'Which tool answers largest equal grouping with no leftovers?', 'A', [('A', 'Greatest common factor'), ('B', 'Least common multiple'), ('C', 'Prime test'), ('D', 'Remainder')], 'A greatest common factor captures the largest shared divisor.', tags=['gcf', 'tool_choice']),
    fixed('ARITH007_LCM_LIST', 'Find LCM(6, 8).', '24', 'The first shared positive multiple is 24.', tags=['lcm']),
    generated('ARITH007_LCM_PRIMES', 'A number has prime factorization 2^{a}×3^{b}. Enter the number.', {'a': v(2, 4), 'b': v(1, 3)}, {'n': '2**a*3**b'}, '{n}', 'Multiply the prime powers: 2^{a}×3^{b}={n}.', tags=['prime_factorization', 'prime_exponents']),
    fixed('ARITH007_GCF_PACK', 'Find the greatest common factor of 84 and 126.', '42', 'Common factors of 84 and 126 have greatest value 42.', tags=['gcf', 'factor_lists']),
    choice('ARITH007_LCM_BELLS', 'Two repeating bells must be synchronized at the earliest future time. Which tool is appropriate?', 'B', [('A', 'GCF'), ('B', 'LCM'), ('C', 'Prime factor count'), ('D', 'Rounding')], 'Earliest shared repetition is a least common multiple question.', tags=['lcm', 'tool_choice']),
    generated('ARITH007_MULTIPLE_STEP', 'A runner marks every {step} metres. Which mark is the {count}th positive multiple of {step}?', {'step': v(4, 9), 'count': v(3, 8)}, {'mark': 'step*count'}, '{mark}', 'The kth positive multiple is k groups of the step, so {count}×{step}.', tags=['multiples', 'sequence']),
    choice('ARITH007_FACTOR_OR_MULTIPLE', 'In 7×8=56, which statement is true?', 'A', [('A', '7 is a factor of 56'), ('B', '7 is a multiple of 56'), ('C', '56 is a factor of 7'), ('D', 'Neither number has a factor relationship')], 'The product equation certifies 7 as a factor of 56.', tags=['language']),
    fixed('ARITH007_FACTOR_PAIR', 'A number is 2²×3¹. How many positive factors does it have?', '6', 'Choose exponents 0,1,2 for 2 and 0,1 for 3, giving 3×2=6 factors.', tags=['factor_count', 'prime_exponents']),
    fixed('ARITH007_SQUARE_MIDDLE', 'Which positive factor pair is the middle pair for 49? Enter the factor.', '7', '49 is a square: 7×7=49, so 7 is the middle factor.', tags=['square_numbers']),
    choice('ARITH007_DIVISIBILITY_FIVE', 'Which test shows that 735 is divisible by 5?', 'C', [('A', 'Its digit sum is 15'), ('B', 'It is odd'), ('C', 'Its last digit is 5'), ('D', 'It has three digits')], 'Divisibility by 5 is determined by a final digit of 0 or 5.', tags=['divisibility', 'last_digit']),
    fixed('ARITH007_IDENTITY_CHECK', 'For positive a=12 and b=18, enter GCF(a,b)×LCM(a,b).', '216', 'GCF=6 and LCM=36; 6×36=216=12×18.', tags=['gcf', 'lcm', 'check']),
    choice('ARITH007_COMMON_MULTIPLE', 'Which number is divisible by both 6 and 9?', 'B', [('A', '18'), ('B', '36'), ('C', '27'), ('D', '45')], '36÷6=6 and 36÷9=4, so 36 is divisible by both.', tags=['divisibility', 'common_multiple']),
    capstone('ARITH007_CAPSTONE', 'A red signal repeats every 8 seconds and a blue signal every 12 seconds; both flash at time 0. Enter the first positive time they flash together.', '24', ['Models each repeat time as a positive multiple and identifies the shared event.', 'Shows that 24 is a common multiple of 8 and 12.', 'Explains why 8, 12, or any smaller positive time is not a common multiple, so 24 is least, with seconds stated.'], 'Multiples of 8 are 8, 16, 24; multiples of 12 are 12, 24. Therefore the first positive shared time is LCM(8,12)=24 seconds.'),
]

figure('arith007-factor-pairs.svg', 'Factor pairs of 36', '<g transform="translate(32 78)"><rect width="155" height="80" fill="#d9eee5"/><rect x="165" width="155" height="80" fill="#d9eee5"/><rect x="330" width="155" height="80" fill="#d9eee5"/><rect x="495" width="155" height="80" fill="#d9eee5"/><text x="78" y="50" text-anchor="middle" font-size="25">1×36</text><text x="243" y="50" text-anchor="middle" font-size="25">2×18</text><text x="408" y="50" text-anchor="middle" font-size="25">3×12</text><text x="573" y="50" text-anchor="middle" font-size="25">4×9</text><text x="0" y="155" font-size="21">6×6 is the middle pair; later pairs would repeat in reverse.</text></g>')
figure('arith007-gcf-lcm.svg', 'GCF and LCM answer different questions', '<circle cx="210" cy="174" r="90" fill="#d9eee5"/><circle cx="350" cy="174" r="90" fill="#f5dfb5"/><text x="176" y="168" font-size="22">GCF</text><text x="153" y="200" font-size="18">shared building</text><text x="315" y="168" font-size="22">LCM</text><text x="295" y="200" font-size="18">shared repeat</text><text x="28" y="320" font-size="21">12 and 18 → GCF 6; 12 and 18 → LCM 36</text>')

save('MATH_ARITH_007', 'Factors, multiples, primes, GCF and LCM', theory, ['MATH_ARITH_006'], examples, apps, questions, [media('arith007-factor-pairs.svg', 'Four factor-pair cards for 36, followed by the square pair 6 times 6.', 'Factor pairs certify divisors by multiplying back to the target.'), media('arith007-gcf-lcm.svg', 'A two-circle comparison labels GCF as shared building and LCM as shared repeat.', 'Choose GCF for exact sharing and LCM for synchronized repetition.')], tags=['arithmetic', 'factors', 'multiples', 'primes', 'gcf', 'lcm'])
