from pathlib import Path
import yaml
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'content/math/algebra_foundations/skills'
MEDIA=ROOT/'content/math/algebra_foundations/skills/media/native-arithmetic-onramp'
MEDIA.mkdir(parents=True,exist_ok=True)
def ex(p,s,e):return dict(prompt=p,solution=s,explanation=e)
def var(a,b):return dict(type='int',min=a,max=b)
def q(id,p,a,e,v=None,d=None,choices=None):
 r=dict(id=id,type='generated' if v else 'fixed',prompt_template=p,variables=v or {},derived=d or {},constraints=[],answer=dict(type='numeric',value=a),grading=dict(method='exact_numeric'),difficulty='medium',answer_mode='final_only',work=dict(mode='none'),review_policy=dict(work_review='none',mastery_requires_review_pass=False,allow_self_review=True),explanation_template=e,mistake_tags=['place_value' if id.startswith('WHOLE') else 'common_units'])
 if choices:r.update(answer=dict(type='choice',value=a),grading=dict(method='multiple_choice'),options=[dict(id=chr(65+i),label=t) for i,t in enumerate(choices)])
 return r
def cap(id,p,a,e,criteria):
 r=q(id,p,a,e);r.update(answer_mode='final_plus_required_work',difficulty='hard',work=dict(mode='rubric_check',prompt='Explain each part in words, with a labelled calculation or drawing if useful. A final number alone is not enough.',rubric=dict(criteria=[dict(id=f'criterion_{i+1}',description=t,weight=2) for i,t in enumerate(criteria)])),review_policy=dict(work_review='tutor_required',mastery_requires_review_pass=True,allow_self_review=False));return r
def media(name,alt,caption):return dict(src='media/native-arithmetic-onramp/'+name+'.svg',alt=alt,caption=caption,width=800,height=360,fit='contain')
def svg(name,title,body):
 (MEDIA/(name+'.svg')).write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 360" width="800" height="360"><rect width="800" height="360" rx="20" fill="#fffdf7"/><g font-family="sans-serif" fill="#163f36"><text x="32" y="42" font-size="25" font-weight="bold">'+title+'</text>'+body+'</g></svg>',encoding='utf-8')
def save(id,name,theory,pre,examples,apps,questions,images):
 assert len(examples)==10 and len(apps)==4 and len(questions)==20
 apps=[dict(title=a['prompt'],description=a['solution']+' '+a['explanation']) if 'prompt' in a else a for a in apps]
 obj=dict(id=id,schema_version='0.2',name=name,domain='Math',subdomain='Arithmetic',topic='Arithmetic Foundations',description=theory.split('\n')[0],prerequisites=pre,tags=['arithmetic','foundations','reasoning'],unlocks=[],mastery=dict(passing_score=.8,minimum_confidence=3,review_after_days_if_mastered=7,review_after_days_if_learning=2),theory=theory,examples=examples,applications=apps,media=images,test=dict(question_count=20,randomize_order=True,questions=questions))
 (OUT/(id+'_'+name.lower().replace(',','').replace('-','_').replace(' ','_')+'.yaml')).write_text(yaml.safe_dump(obj,sort_keys=False,allow_unicode=True,width=105),encoding='utf-8')
whole='''Whole numbers count complete units: 0, 1, 2, 3, and so on. This is an entry point; you do not need signed-number rules first.

Read a number by place value, not by the size of its digits. In 40,306, the 4 represents four ten-thousands, the 3 three hundreds, the 0 no tens, and the 6 six ones. Zero is a placeholder: 406 and 46 are different. Expanded notation is 40,000 + 300 + 6. A comma here separates groups of three digits; it is not a decimal point. To compare nonnegative whole numbers, first compare the number of digits (ignoring leading zeros), then compare from the left until a place differs. On a number line, larger numbers lie farther right. Zero counts an empty collection, not a missing answer.

Addition combines amounts measured in the same unit. It can also describe moving forward or increasing a starting amount. In 278 + 156, combine ones: 8 + 6 = 14 ones. Exchange ten ones for one ten and keep four ones. Seven tens plus five tens plus the exchanged ten make thirteen tens: exchange ten tens for one hundred. The final result is 434. A carried 1 is one unit of the next place, not an extra single object. Align ones with ones. Adding 0 changes nothing, and the order of two addends does not change their sum.

Subtraction can remove objects, compare two amounts, or find a missing addend. For 402 - 178, there are not enough ones or tens to subtract directly. Exchange one hundred into ten tens, then one of those tens into ten ones. The same 402 is now 3 hundreds, 9 tens and 12 ones. Subtract by place to get 224. Regrouping changes the representation, not the total. Check with 178 + 224 = 402. You cannot generally reverse subtraction: 8 - 3 is not 3 - 8. In this lesson, removal calculations keep nonnegative answers; signed numbers come next.

Multiplication counts equal groups. Four rows of six tiles give 4 times 6 = 24 tiles. Rotating the array shows why 6 times 4 has the same total. Decomposing an array explains distribution: 7 times 23 = 7 times 20 + 7 times 3 = 161. The 2 in 23 represents twenty, so its partial product is 140, not 14. Multiplying by 1 preserves an amount; multiplying by 0 gives no objects. Addition of unequal groups cannot always be replaced by one multiplication without further work.

Division has two useful meanings. Sharing 24 tiles among 6 children asks how many tiles per child: 4. Grouping 24 tiles into groups of 6 asks how many groups: also 4, but the answer has a different meaning. In a whole-number calculation with divisor d greater than zero, dividend = d times quotient + remainder, where 0 <= remainder < d. Thus 29 divided by 6 is 4 remainder 5 because 29 = 6 times 4 + 5. A remainder of 6 would make another full group. Dividing zero by a positive number gives zero. Division by zero is undefined: no number of zero-sized groups makes a positive total, and zero divided by zero would not select a unique quotient.

A context decides what to do with a remainder. To carry 29 pupils in six-seat vehicles, four vehicles are insufficient: five are needed. To fill six-item sealed boxes from 29 items, only four full boxes can be sold, with five items left. If 29 litres can be shared continuously among six containers, each can receive 4 and 5/6 litres. These are different questions about the same division. Read what the answer counts before rounding or discarding anything.

A good calculation includes a plan, the operation, the unit, and a check. Estimate 398 + 205 as about 400 + 200 = 600 before calculating exactly 603. Estimates detect an implausible place-value slip but are not exact answers. Use inverse operations to check: addition undoes subtraction, and multiplication checks division when the remainder is included. For a two-stage story, identify what happens first and label its intermediate result. Do not combine unlike units or let a keyword replace understanding. The reviewed capstone asks you to explain grouping and the meaning of a remainder as well as find a number.'''
we=[ex('Write 50,204 in expanded notation.','50,000 + 200 + 4','The 5 is in the ten-thousands place. Zeros preserve the empty thousands and tens places.'),ex('Which is greater: 39,980 or 40,002?','40,002','Compare the ten-thousands place first: four ten-thousands exceed three, regardless of later digits.'),ex('Calculate 278 + 156.','434','14 ones become 1 ten and 4 ones; 13 tens become 1 hundred and 3 tens; four hundreds remain.'),ex('Calculate 402 - 178.','224','Rewrite 402 as 3 hundreds, 9 tens, 12 ones. Subtract 1 hundred, 7 tens, 8 ones. Check 224 + 178 = 402.'),ex('An array has 4 rows of 6 tiles. How many tiles?','24 tiles','Each of four rows contributes six, so 6+6+6+6=24. Rotating the array gives six rows of four.'),ex('Calculate 7 times 23 by decomposition.','161','7(20+3)=140+21. Both parts must be multiplied; the tens contribute 140.'),ex('Share 24 counters equally among 6 people.','4 counters each','Six equal shares of four reconstruct 24. The quotient counts counters in each share.'),ex('Put 24 counters in bags of 6. How many bags?','4 bags','Repeatedly remove a group of six. Here the quotient counts groups, not counters per person.'),ex('Divide 29 by 6 as a whole-number quotient and remainder.','4 remainder 5','6 times 4 + 5 = 29 and 0 <= 5 < 6. A remainder at least six would allow another group.'),ex('A trip has 29 pupils and vehicles hold 6 pupils. How many vehicles?','5 vehicles','Four carry only 24. The five remaining pupils need one additional vehicle, even though it is not full.')]
we[2]['math_blocks']=[dict(type='derivation',steps=['278 + 156','(200 + 100) + (70 + 50) + (8 + 6)','300 + 120 + 14','434'],alt='Addition regrouped by place value',linear_text='278 plus 156 equals 300 plus 120 plus 14, which equals 434.')]
wa=[ex('A shop receives 125 notebooks and then 78 more. It sells 96. How many remain?','107 notebooks','First find 203 delivered, then subtract 96. Check 107 + 96 = 203.'),ex('Six shelves hold 18 books each. Find the total.','108 books','Six equal groups: 6(10+8)=60+48. The unit is books, not shelves.'),ex('There are 53 biscuits, with 8 in each complete gift box. How many complete boxes and leftovers?','6 boxes and 5 biscuits','53 = 8 times 6 + 5. Do not count the incomplete seventh box as complete.'),ex('One walking route is 1,204 m and another is 985 m. How much longer is the first?','219 m','Subtraction compares the lengths; 985 + 219 = 1,204 checks the difference.')]
wq=[]
wq.append(q('WHOLE_PLACE','In {number}, what is the value of the digit {h} in the hundreds place?','{value}','Hundreds have value digit times 100.',{'h':var(1,9),'t':var(0,9),'u':var(0,9)},{'number':'100*h+10*t+u','value':'100*h'}))
wq.append(q('WHOLE_EXPAND','Write the number represented by {k} thousands + {h} hundreds + {u} ones.','{value}','The absent tens contribute zero; keep that place.',{'k':var(1,9),'h':var(1,9),'u':var(1,9)},{'value':'1000*k+100*h+u'}))
wq.append(q('WHOLE_COMPARE','Which is larger: {a} or {b}? Enter the larger number.','{b}','Compare the thousands before the remaining digits.',{'k':var(1,8)},{'a':'1000*k+999','b':'1000*(k+1)+1'}))
wq.append(q('WHOLE_ADD','Calculate {a} + {b}.','{c}','Add matching place values; exchange ten ones or tens when necessary.',{'a':var(178,298),'b':var(156,287)},{'c':'a+b'}))
wq.append(q('WHOLE_SUB','Calculate {a} - {b}.','{c}','Regroup across zero tens, keeping the original value unchanged.',{'h':var(3,9),'b':var(115,198)},{'a':'100*h+2','c':'a-b'}))
wq.append(q('WHOLE_MISSING','Find the missing addend: {a} + ? = {total}.','{b}','Subtract the known part from the whole.',{'a':var(100,400),'b':var(40,200)},{'total':'a+b'}))
wq.append(q('WHOLE_ARRAY','An array has {r} rows with {c} dots per row. How many dots?','{n}','Rows are equal groups: multiply rows by dots per row.',{'r':var(3,8),'c':var(4,9)},{'n':'r*c'}))
wq.append(q('WHOLE_DISTRIBUTE','Calculate {m} times {n} using tens and ones.','{ans}','Multiply both place-value parts, then add the partial products.',{'m':var(3,9),'t':var(2,8),'u':var(2,9)},{'n':'10*t+u','ans':'m*n'}))
wq.append(q('WHOLE_SHARE','Share {n} counters equally among {d} people. How many per person?','{quot}','Each equal share contains {quot}; multiplying by {d} checks the total.',{'d':var(2,9),'quot':var(3,12)},{'n':'d*quot'}))
wq.append(q('WHOLE_GROUP','Put {n} counters into bags of {d}. How many bags?','{quot}','The quotient counts complete groups of size {d}.',{'d':var(3,9),'quot':var(4,12)},{'n':'d*quot'}))
wq.append(q('WHOLE_REMAINDER','Divide {n} by {d}. Enter only the remainder.','{rem}','{n} = {d} times {quot} + {rem}, and the remainder is smaller than the divisor.',{'d':var(4,9),'quot':var(3,12),'rem':var(1,3)},{'n':'d*quot+rem'}))
wq.append(q('WHOLE_FULL_BOXES','Pack {n} items into complete boxes of {d}. How many complete boxes?','{quot}','The leftover item cannot form another complete box.',{'d':var(3,9),'quot':var(3,10)},{'n':'d*quot+1'}))
wq.append(q('WHOLE_VEHICLES','Carry {n} pupils in vehicles with {d} pupil seats each. Minimum vehicles?','{ans}','The remainder needs an additional vehicle.',{'d':var(4,9),'quot':var(3,8)},{'n':'d*quot+1','ans':'quot+1'}))
wq.append(q('WHOLE_RECONSTRUCT','A division by {d} has quotient {quot} and remainder 2. What was the dividend?','{n}','Reconstruct divisor times quotient plus remainder.',{'d':var(3,9),'quot':var(3,12)},{'n':'d*quot+2'}))
wq.append(q('WHOLE_ZERO','Which statement is correct?','C','Zero divided by a positive number is zero; division by zero is undefined.',choices=['7 divided by 0 is 0','0 divided by 0 is 1','0 divided by 7 is 0','7 times 0 is 7']))
wq.append(q('WHOLE_ERROR','A learner says 6 times 24 = 12 + 24 = 36. What went wrong?','B','The 2 means twenty. Its partial product is 6 times 20 = 120.',choices=['Multiplication cannot be split','The tens partial product should be 120, not 12','The ones partial product should be 4','Nothing went wrong']))
wq.append(q('WHOLE_ESTIMATE','Before calculating 398 + 205 exactly, which is the useful nearest-hundred estimate?','B','400 + 200 = 600 is an estimate, while the exact answer is 603.',choices=['60','600','6,000','603 is the nearest-hundred estimate']))
wq.append(q('WHOLE_COMPARE_GAP','One collection has {a} stamps and another has {b}. How many more in the first?','{gap}','A comparison asks for the difference, not the sum.',{'b':var(80,200),'gap':var(25,90)},{'a':'b+gap'}))
wq.append(q('WHOLE_TWO_STAGE','There are {r} trays of {c} rolls. {sold} rolls are sold. How many remain?','{ans}','Multiply to count the starting rolls, then subtract those sold.',{'r':var(4,9),'c':var(5,10),'sold':var(2,15)},{'ans':'r*c-sold'}))
wq.append(cap('WHOLE_CAPSTONE','There are 29 pupils and each vehicle has 6 pupil seats. Enter the minimum number of vehicles, then explain what 29 divided by 6 means here, how to check its remainder, and why the remainder changes the answer.','5','29 = 6 times 4 + 5. Four full vehicles leave five pupils, so a fifth is needed. Five is less than six, as a remainder must be.',['Explains grouping pupils into six-seat vehicles, with the quotient counting full groups.','Uses 29 = 6 times 4 + 5 and verifies 0 <= 5 < 6.','Explains why four vehicles are insufficient and five are sufficient, with correct units.']))
svg('whole-place-value','40,306: every digit has a place',''.join(f'<rect x="{32+i*148}" y="80" width="140" height="160" fill="#e5eee8"/><text x="{102+i*148}" y="115" text-anchor="middle" font-size="17">{label}</text><text x="{102+i*148}" y="179" text-anchor="middle" font-size="36">{digit}</text>' for i,(label,digit) in enumerate(zip(['Ten-thousands','Thousands','Hundreds','Tens','Ones'],'40306')))+'<text x="32" y="300" font-size="23">40,000 + 300 + 6 = 40,306</text>')
svg('whole-array','4 rows of 6: equal groups', ''.join(f'<circle cx="{65+c*55}" cy="{95+r*48}" r="15" fill="#287365"/>' for r in range(4) for c in range(6))+'<text x="430" y="130" font-size="23">6 + 6 + 6 + 6</text><text x="430" y="177" font-size="23">4 × 6 = 24 tiles</text><text x="32" y="325" font-size="19">Rotate the array: 6 rows of 4 still contain 24 tiles.</text>')
save('MATH_ARITH_006','Whole-number calculation and place value',whole,[],we,wa,wq,[media('whole-place-value','A table shows 4 ten-thousands, 0 thousands, 3 hundreds, 0 tens and 6 ones.','A zero keeps an empty place visible.'),media('whole-array','Twenty-four dots arranged in four rows of six.','Multiplication counts equal groups; both factors have a meaning.')])
fraction='''Fractions count equal-sized parts of a chosen whole. Adding and subtracting them means combining or comparing numbers measured in the same unit. Begin with positive amounts; the signed cases later use Integer operations (MATH_ARITH_001).

With a common denominator, the unit already matches: 2/7 + 3/7 = 5/7. Count two sevenths and three sevenths. The denominator stays seven because adding portions does not change the size of each portion. Likewise, 6/9 - 2/9 = 4/9. Fractions may exceed one: 9/7 means one whole and two sevenths. A large numerator is not itself an error.

Unlike denominators require a common unit. To add 1/2 and 1/3 of the same whole, split each half into three sixths and each third into two sixths. The amounts do not change: 1/2 = 3/6 and 1/3 = 2/6. Now count 3/6 + 2/6 = 5/6. The incorrect answer 2/5 is smaller than 1/2 even though a positive amount was added. More fundamentally, adding denominators invents a new unit without preserving either original fraction. Pictures must use the same-sized whole: half a small pizza and a third of a large pizza cannot be combined as fractions of one unspecified pizza.

A common multiple of the denominators supplies a common denominator. The least common multiple is efficient but not compulsory. For 1/6 + 1/4, twelfths give 2/12 + 3/12 = 5/12. Twenty-fourths give 4/24 + 6/24 = 10/24, the same value. Multiply both numerator and denominator by the same nonzero number to preserve a fraction; changing only the denominator changes its value. If one denominator divides the other, use the larger: 3/8 + 1/4 = 3/8 + 2/8 = 5/8. Simplify your final fraction when useful. Equivalent exact fractions describe the same number even when written differently.

Subtraction uses the same unit rule. For 5/6 - 1/4, write 10/12 - 3/12 = 7/12. Do not subtract denominators or reverse the numerator subtraction to force a positive answer. For a missing addend, subtract the known part from the total: 2/5 + x = 7/10 gives x = 7/10 - 4/10 = 3/10. Check by adding the result back.

Mixed notation combines a whole number with a proper fraction. The number 2 3/5 means 2 + 3/5, not multiplication. Two wholes contain ten fifths, so 2 3/5 = 13/5. Conversely, 17/6 = 2 5/6 because 17 = 6 times 2 + 5. On this lesson's answer line use an improper fraction such as 13/5 rather than mixed notation unless asked for just a whole part or numerator. This avoids ambiguity while keeping an exact answer.

For mixed-number addition, convert first or add whole and fractional parts carefully. In 1 3/4 + 2 2/3, the whole parts make 3 and the fractional parts make 9/12 + 8/12 = 17/12 = 1 5/12. Combine them to obtain 4 5/12, or 53/12. Do not lose the extra whole created by the fractional sum.

For mixed subtraction, exchange a whole if the first fractional part is too small. The calculation 3 1/4 - 1 2/3 becomes 2 15/12 - 1 8/12 = 1 7/12. Exchanging a whole adds twelve twelfths to the fractional part while removing one from the whole part; it does not change the starting number. Subtracting the whole parts and then reversing the fractional subtraction is invalid. Improper fractions independently check the result: 39/12 - 20/12 = 19/12.

Signed fractions follow number-line addition. For -1/2 + 3/4, start at -2/4 and move three quarter-units right, ending at 1/4. For 1/3 - (-1/6), subtracting a negative adds a positive: 2/6 + 1/6 = 1/2. A negative mixed amount, minus two and one third, means -(2+1/3) = -7/3, not -2+1/3. Parentheses make the intended sign explicit. Review signed integers first if this section is unfamiliar.

Interpret and check. A sum of positive fractions exceeds each addend. Subtracting a smaller positive amount reduces a positive starting quantity. Length, time and capacity problems need matching measurement units and a shared reference whole. Explain why the conversion preserves the amount, then explain the operation. The capstone requires equal-unit reasoning and error analysis; the number 5/6 alone does not demonstrate understanding.'''
fe=[ex('Calculate 2/7 + 3/7.','5/7','Both count sevenths. Add their counts without changing that unit.'),ex('Calculate 1/2 + 1/3.','5/6','Split the same whole into sixths: 3/6 + 2/6 = 5/6.'),ex('Calculate 1/6 + 1/4 using two common denominators.','5/12','Twelfths give 2/12+3/12; twenty-fourths give 4/24+6/24=10/24=5/12.'),ex('Calculate 5/6 - 1/4.','7/12','Convert to 10/12-3/12. Subtract counts of twelfths.'),ex('Write 2 3/5 as an improper fraction.','13/5','Two wholes are ten fifths; add three more fifths.'),ex('Calculate 1 3/4 + 2 2/3.','53/12','21/12+32/12=53/12, or 4 5/12. The fractional sum contributes another whole.'),ex('Calculate 3 1/4 - 1 2/3.','19/12','Exchange a whole: 2 15/12 - 1 8/12=1 7/12. Check 39/12-20/12.'),ex('Calculate -1/2 + 3/4.','1/4','-2/4+3/4=1/4. A rightward move crosses zero.'),ex('Calculate 1/3 - (-1/6).','1/2','Subtracting a negative adds: 2/6+1/6=3/6=1/2.'),ex('Find x in 2/5 + x = 7/10.','3/10','7/10-4/10=3/10; adding 4/10 back checks the answer.')]
fe[1]['math_blocks']=[dict(type='derivation',steps=['1/2 + 1/3','3/6 + 2/6','5/6'],alt='Halves and thirds converted to sixths',linear_text='One half plus one third equals three sixths plus two sixths, which equals five sixths.')]
fa=[ex('Walk 3/4 km then 2/3 km. Find the total.','17/12 km','9/12+8/12=17/12. The total is greater than one kilometre.'),ex('Pour 5/6 litre from a jug containing 2 1/4 litres. What remains?','17/12 litres','27/12-10/12=17/12. Subtract from the original capacity.'),ex('Preparation takes 1/3 hour and finishing takes 1/4 hour. Total time?','7/12 hour','4/12+3/12=7/12 hour; 20+15=35 minutes checks the result.'),ex('Cut 3/5 m and 1/4 m from a 2 m ribbon. What remains?','23/20 m','40/20-12/20-5/20=23/20. Subtract both cuts.')]
fq=[]
fq.append(q('FRADD_SAME','Calculate {a}/{d} + {b}/{d}. Enter an exact fraction.','{n}/{d}','Add counts of the same fractional unit.',{'a':var(1,4),'b':var(1,4),'d':var(5,12)},{'n':'a+b'}))
fq.append(q('FRADD_SUB_SAME','Calculate {a}/{d} - {b}/{d}.','{n}/{d}','Subtract numerators; keep the common unit.',{'a':var(6,9),'b':var(1,4),'d':var(10,15)},{'n':'a-b'}))
fq.append(q('FRADD_UNLIKE','Calculate 1/{d} + 1/{e}.','{n}/{den}','Convert to {e}/{den}+{d}/{den}.',{'d':var(2,6),'e':var(7,11)},{'den':'d*e','n':'d+e'}))
fq.append(q('FRADD_NESTED','Calculate 1/{d} + {a}/{den}.','{n}/{den}','The first numerator becomes {k} after making equivalent fractions.',{'d':var(2,6),'k':var(2,4),'a':var(1,3)},{'den':'d*k','n':'k+a'}))
fq.append(q('FRADD_SUB_UNLIKE','Calculate {a}/{d} - 1/{e}.','{n}/{den}','Use denominator {den} and preserve the subtraction order.',{'d':var(3,7),'e':var(8,12)},{'a':'d-1','den':'d*e','n':'a*e-d'}))
fq.append(q('FRADD_EQUIVALENT','Write 1/{d} with denominator {den}. Enter only the numerator.','{k}','Multiply the numerator by the same factor as the denominator.',{'d':var(2,9),'k':var(2,6)},{'den':'d*k'}))
fq.append(q('FRADD_MIXED_CONVERT','Convert {w} and 1/{d} to an improper fraction.','{n}/{d}','Count fractional units in the whole part before adding one more.',{'w':var(2,6),'d':var(3,9)},{'n':'w*d+1'}))
fq.append(q('FRADD_IMPROPER_WHOLE','Write {n}/{d} as a mixed number. Enter only the whole-number part.','{w}','{n}={d} times {w}+1.',{'w':var(2,7),'d':var(3,9)},{'n':'w*d+1'}))
fq.append(q('FRADD_MIX_ADD','Calculate ({w}+3/4)+({v}+2/3). Enter an improper fraction.','{n}/12','The fractional sum 17/12 contributes an additional whole.',{'w':var(1,5),'v':var(1,5)},{'n':'12*(w+v)+17'}))
fq.append(q('FRADD_REGROUP','Calculate ({w}+1/4)-(1+2/3). Enter an exact fraction.','{n}/12','Exchange one whole for twelve twelfths before subtracting.',{'w':var(3,7)},{'n':'12*w-17'}))
fq.append(q('FRADD_FROM_WHOLE','Calculate {w}-{a}/{d}.','{n}/{d}','Write the whole number using the fractional unit first.',{'w':var(2,6),'a':var(1,3),'d':var(4,9)},{'n':'w*d-a'}))
fq.append(q('FRADD_MISSING','Find x: 1/{d}+x={a}/{den}.','{n}/{den}','Subtract 2/{den} from the total.',{'d':var(3,7),'a':var(3,5)},{'den':'2*d','n':'a-2'}))
fq.append(q('FRADD_SIGNED','Calculate -1/{d}+3/{den}.','1/{den}','Convert the negative amount to -2/{den}, then add.',{'d':var(2,8)},{'den':'2*d'}))
fq.append(q('FRADD_NEGATIVE_SUB','Calculate 1/{d}-(-1/{den}).','3/{den}','Subtracting a negative adds a positive.',{'d':var(2,8)},{'den':'2*d'}))
fq.append(q('FRADD_CONTEXT','A ribbon is {w} m long. Cut off 1/{d} m and 1/{e} m. Metres remaining?','{n}/{den}','Use a common unit and subtract both cuts.',{'w':var(2,5),'d':var(2,6),'e':var(7,10)},{'den':'d*e','n':'w*den-e-d'}))
fq.append(q('FRADD_WRONG_DEN','Why is 1/2+1/3=2/5 incorrect?','B','Halves and thirds must be replaced by equivalent amounts in the same unit.',choices=['The numerator must stay one','It combines counts of unequal units without equivalent fractions','Fractions cannot exceed one','Addition of fractions is impossible']))
fq.append(q('FRADD_COMMON_NOT_LEAST','Is denominator 24 valid for 1/6+1/4?','C','4/24+6/24=10/24=5/12. Least is efficient, not mandatory.',choices=['No, only the least denominator works','Yes, giving 2/24','Yes, if both fractions are converted correctly','No, the denominator must be 10']))
fq.append(q('FRADD_MIX_ERROR','A learner writes 3 1/4 - 1 2/3 = 2 5/12 by reversing the fractional subtraction. Choose the correction.','A','39/12-20/12=19/12; subtraction order cannot be reversed.',choices=['19/12, using regrouping or improper fractions','The original answer is correct','Only the whole parts should be subtracted','Add the denominators']))
fq.append(q('FRADD_REFERENCE','Is half a small pizza plus a third of a large pizza automatically five sixths of one pizza?','B','A common-sized reference whole is essential.',choices=['Yes, sizes never matter','No, first specify the reference whole','Yes, by adding denominators','Fractions cannot describe pizza']))
fq.append(cap('FRADD_CAPSTONE','Calculate 1/2+1/3 of the same whole. Enter an exact fraction, then explain with equal units why it is correct and why 2/5 is not.','5/6','1/2=3/6 and 1/3=2/6, so the sum is 5/6. Adding denominators changes the unit. Also 2/5<1/2 cannot result from adding a positive amount.',['Explains a shared whole subdivided into sixths.','Preserves both amounts and counts five sixths.','Explains the denominator error and supplies a valid magnitude check or counterexample.']))
svg('fraction-sixths','Same whole, shared unit',''.join('<text x="30" y="'+str(99+r*75)+'" font-size="22">'+label+'</text>'+''.join(f'<rect x="{180+i*85}" y="{65+r*75}" width="85" height="48" fill="'+('#287365' if i<n else '#e5eee8')+'" stroke="#163f36"/>' for i in range(6)) for r,(label,n) in enumerate([('1/2 = 3/6',3),('1/3 = 2/6',2),('sum = 5/6',5)]))+'<text x="30" y="325" font-size="19">Subdivision changes the labels, not the amounts.</text>')
svg('fraction-beyond-one','Fractions are numbers beyond one whole','<path d="M70 170H730" stroke="#163f36" stroke-width="3"/>'+''.join(f'<path d="M{70+i*55} 158v24" stroke="#163f36"/>' for i in range(13))+''.join(f'<text x="{70+i*55}" y="213" text-anchor="middle" font-size="17">{label}</text>' for i,label in [(0,'0'),(3,'1/2'),(6,'1'),(9,'3/2'),(12,'2')])+'<circle cx="565" cy="170" r="9" fill="#bb5538"/><text x="390" y="105" font-size="24">9/6 = 3/2 = 1 + 1/2</text><text x="40" y="296" font-size="20">Each small interval is one sixth of the same unit.</text>')
save('MATH_ARITH_008','Adding and subtracting fractions and mixed numbers',fraction,['MATH_ARITH_003','MATH_ARITH_007'],fe,fa,fq,[media('fraction-sixths','Three equal strips divided into six parts show three sixths, two sixths, and five sixths.','Common denominators give common-sized units.'),media('fraction-beyond-one','A number line marks sixths from zero to two, with three halves highlighted.','Fractions can lie beyond one whole.')])
