"""Build the content-matched illustration library: python -m scripts.build_lesson_illustrations."""
from pathlib import Path
import argparse,hashlib,json
import matplotlib
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg
from scripts import illustration_math,illustration_programming,illustration_geography,illustration_trigonometry,illustration_concepts
from scripts.illustration_drawing import PAPER
from scripts.illustration_captions import CAPTIONS

ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/"docs/assets/media/lesson-illustrations"
EXTRAS={"MATH_TRIG_001":["special-triangles","elevation"],"MATH_TRIG_002":["radian-arc","reference-turns"],"MATH_TRIG_003":["period-phase"],"MATH_TRIG_004":["quadrant-signs"],"MATH_TRIG_005":["restricted-cycles","tangent"],"MATH_TRIG_006":["ssa","included-area"],"CUSTOM_PROG_028":["recursion-stack","memoization"]}
EXTRAS.update({"MATH_ARITH_004":["fraction-division"],"MATH_INEQ_001":["interval-union"],"MATH_FUNC_001":["function-mapping"],"MATH_LOG_001":["shifted-log-domain"],"MATH_SYS_001":["system-cases"],"CUSTOM_PROG_023":["binary-search"]})

def fingerprint(skill):
    parts=[skill["name"].strip(),skill["theory"].strip()]
    for example in skill.get("examples",[]):parts.extend([str(example.get("prompt","")).strip(),str(example.get("solution","")).strip()])
    value=2166136261
    for char in "\u241e".join(parts):value=((value^ord(char))*16777619)&0xffffffff
    return f"{value:08x}"

def build(preview=None):
    native=json.loads((ROOT/"docs/curriculum-data.json").read_text(encoding="utf-8"))
    skills=list(native["skills"])
    for folder in sorted((ROOT/"docs/lesson-depot/lessons").iterdir()):
        versions=sorted(folder.glob("*/lesson-set.json"),key=lambda p:tuple(map(int,p.parent.name.split("."))))
        if versions:skills+=json.loads(versions[-1].read_text(encoding="utf-8"))["skills"]
    OUTPUT.mkdir(parents=True,exist_ok=True)
    if preview:preview.mkdir(parents=True,exist_ok=True)
    records={}
    with matplotlib.rc_context({"text.usetex":False,"svg.fonttype":"none","svg.hashsalt":"quickmaths-illustrations-v1","font.family":"DejaVu Sans"}):
        for skill in skills:
            has_media=any(row.get("media") for row in [skill,*skill.get("examples",[]),*skill.get("applications",[])])
            kinds=[] if has_media else [skill["id"]]
            kinds+=EXTRAS.get(skill["id"],[])
            if not kinds:continue
            record={"name":skill["name"],"fingerprint":fingerprint(skill),"media":[],"assets":[]}
            for kind in kinds:
                module=illustration_concepts if kind in illustration_concepts.KINDS else illustration_trigonometry if kind!=skill["id"] else illustration_programming if kind.startswith("CUSTOM_PROG") else illustration_geography if kind.startswith("GEO_") else illustration_math
                fig=Figure(figsize=(8.6,6.4),dpi=100,facecolor=PAPER);FigureCanvasAgg(fig)
                ax=fig.add_axes((.12,.14,.83,.75),facecolor=PAPER)
                module.draw(ax,kind)
                # Figure text is also available as a meaningful alternative description.
                labels=[t.get_text().replace("\n"," ") for t in ax.texts if t.get_text()]
                title=ax.get_title()
                alt=(title+". " if title else "")+"; ".join(labels)
                caption=CAPTIONS[kind]
                alt=(caption+" Diagram labels: "+alt)[:990]
                from io import BytesIO
                buffer=BytesIO();fig.savefig(buffer,format="svg",metadata={"Date":None,"Creator":"QuickMaths"})
                data=("\n".join(line.rstrip() for line in buffer.getvalue().decode("utf-8").splitlines())+"\n").encode("utf-8")
                digest=hashlib.sha256(data).hexdigest();filename=f"{kind.lower().replace('_','-')}-{digest[:12]}.svg"
                (OUTPUT/filename).write_bytes(data)
                path=f"media/lesson-illustrations/{filename}"
                record["assets"].append({"path":path,"mime_type":"image/svg+xml","sha256":digest,"bytes":len(data)})
                record["media"].append({"type":"image","src":path,"alt":alt,"caption":caption,"width":860,"height":640})
                if preview:fig.savefig(preview/f"{kind}.png")
                fig.clear()
            records[skill["id"]]=record
    out="// Generated by scripts/build_lesson_illustrations.py. Do not edit by hand.\nexport const LESSON_ILLUSTRATIONS = "+json.dumps(records,ensure_ascii=False,indent=2)+";\n"
    (ROOT/"docs/lesson-illustration-data.js").write_text(out,encoding="utf-8",newline="\n")
    print(f"Built {sum(len(r['media']) for r in records.values())} illustrations for {len(records)} lessons.")

if __name__=="__main__":
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument("--preview-dir",type=Path)
    build(parser.parse_args().preview_dir)
