"""Build MATH_ARITH_009: decimal operations, powers of ten and quotient scaling."""
from native_number_foundations_common import *

theory = '''Decimals extend place value to parts smaller than one whole. The tenths place is 1/10, the hundredths place is 1/100, and the thousandths place is 1/1000. In 4.307, the 4 means four ones, the 3 means three tenths, the 0 means no hundredths, and the 7 means seven thousandths. Trailing zeros do not change a value: 2.5 = 2.50 = 2.500. They can make alignment visible, so write equal numbers of decimal places before adding or subtracting.

Addition and subtraction combine quantities measured in the same unit. Align decimal points vertically, then add or subtract each place. For 6.40 + 2.375, write 6.400 + 2.375 = 8.775. The zeros are placeholders, not new quantity. Estimate first: 6.4+2.4 is about 8.8, so 8.775 is plausible. In a difference such as 10.000 - 3.68, write 3.680 and regroup across places. Check subtraction by adding the difference back to the smaller amount.

Multiplication by a whole number is repeated addition; multiplication by a decimal can be understood by place value and an area model. Compute 2.4×3 by first thinking 24 tenths×3 = 72 tenths = 7.2. For 0.6×0.4, six tenths times four tenths gives 24 hundredths, or 0.24. Count total decimal places in the factors as a useful placement check, then estimate the size. Multiplying by a number between 0 and 1 makes a positive amount smaller; multiplying by a number greater than 1 makes it larger.

Decimal division asks how many groups of a chosen size fit, or how much each share receives. If 8.4 litres are shared into 4 equal containers, 8.4÷4=2.1 litres each. If 8.4 metres are cut into 0.7-metre pieces, 8.4÷0.7 asks for the number of pieces, which is 12. The divisor is the unit being counted, so it cannot be zero. Division by a number between 0 and 1 can produce a larger quotient because many small groups fit in the dividend.

Powers of ten explain place shifts. Multiplying by 10 moves every digit one place left: 3.47×10=34.7. Multiplying by 100 moves two places; dividing by 10 moves one place right. These are place-value changes, not a magical rule about “moving the decimal” without tracking zeros. For 0.058×1000, the 5 moves from hundredths to tens, giving 58. Dividing 5800 by 100 gives 58. If there are not enough written digits, add zeros as placeholders: 4.2÷100=0.042.

Scaling both dividend and divisor by the same nonzero power of ten leaves a quotient unchanged. This is how we make a decimal divisor a whole number: 3.6÷0.12 becomes 360÷12=30 after multiplying both numbers by 100. Scaling only the dividend changes the answer by a factor of 100; scaling only the divisor changes it in the opposite direction. Write the equality explicitly: (a×100)/(b×100)=a/b. The operation is a value-preserving rewrite, not a license to alter one part of a fraction.

Units keep decimal operations meaningful. A price of 2.40 dollars plus 0.75 dollars is 3.15 dollars; a length of 2.40 m cannot be added to 0.75 kg. In a multi-step situation, carry a unit with each intermediate value and round only when the context requires it. Keep exact decimal values while calculating so that early rounding does not accumulate error. If a display reports money to cents, explain whether the stored calculation was exact and the final display was rounded.

Use three checks: estimate the size, verify place alignment, and reverse with an inverse operation when possible. A quotient times its divisor should reconstruct the dividend, up to any stated rounding. The capstone asks you to explain why both entries are scaled when a decimal divisor is cleared and to interpret the quotient with units.
A quotient can be read in two distinct ways. If 8.4 litres are poured into 0.7-litre bottles, 8.4÷0.7 counts bottles; if 8.4 litres are shared among 0.7 groups, the context is different. The divisor is never just a number to manipulate: it names the unit or group size. When a quotient is larger than the dividend, ask whether the divisor is a positive fraction smaller than one; twelve 0.7-metre segments can fit in 8.4 metres even though 12 is larger than 8.4. This size check prevents a rule learned for whole-number divisors from becoming a false universal.

Decimal notation also supports exact fractions. Terminating decimals such as 0.125 represent 125/1000 and can be simplified to 1/8. Repeating decimals require a stated rounding policy if a display is finite. In a financial or scientific calculation, preserve a terminating exact value through the intermediate steps and round only at the reporting boundary. If an answer is a measured approximation, carry its uncertainty rather than suggesting that every displayed digit was known exactly.
'''

examples = [
    example('Add 6.40 and 2.375.', '8.775', 'Write 6.400 so decimal places align, then add by place.'),
    example('Subtract 3.68 from 10.', '6.32', 'Write 10.00−3.68; regrouping gives 6.32.'),
    example('Multiply 2.4 by 3.', '7.2', '24 tenths×3=72 tenths=7.2.'),
    example('Multiply 0.6 by 0.4.', '0.24', 'Six tenths times four tenths is 24 hundredths.'),
    example('Divide 8.4 by 4.', '2.1', 'Four equal groups of 2.1 reconstruct 8.4.'),
    example('Divide 8.4 by 0.7.', '12', 'Scale both by 10: 84÷7=12 pieces.'),
    example('Compute 3.47×100.', '347', 'Each digit shifts two places left; 3.47 becomes 347.'),
    example('Compute 4.2÷100.', '0.042', 'Two place shifts right require a zero placeholder.'),
    example('Compute 3.6÷0.12 by scaling.', '30', 'Multiply dividend and divisor by 100: 360÷12=30.'),
    example('Why does 0.50 equal 0.5?', 'Both are five tenths.', 'The trailing zero adds no hundredths; it can help show alignment.'),
]
apps = [
    application('Money and receipts', 'Decimal addition, subtraction, and final cent display keep prices, tax, and change tied to dollars and cents.'),
    application('Recipe scaling', 'Multiplication and division scale ingredient amounts while preserving the unit of cups, grams, or litres.'),
    application('Rates and data', 'A decimal divisor can represent a unit rate such as metres per segment or litres per container.'),
    application('Sensors and measurements', 'Powers of ten convert milli-, base-, and kilo-units, while quotient checks expose misplaced decimal points.'),
]
v = lambda lo, hi: {"type": "int", "min": lo, "max": hi}
questions = [
    generated('ARITH009_ADD_TENTHS', 'Add {left} and {right}. Enter the decimal sum.', {'a': v(10, 49), 'b': v(10, 49)}, {'left': 'a/10', 'right': 'b/10', 'sum': '(a+b)/10'}, '{sum}', 'Align decimal points; both displayed addends are tenths.', tags=['decimal_addition', 'tenths']),
    generated('ARITH009_SUB_HUNDREDTHS', 'Subtract {right} from {left}. Enter the decimal difference.', {'a': v(40, 99), 'b': v(10, 39)}, {'left': 'a/100', 'right': 'b/100', 'difference': '(a-b)/100'}, '{difference}', 'Subtract aligned hundredths after displaying both decimal values.', tags=['decimal_subtraction', 'hundredths']),
    generated('ARITH009_WHOLE_MULTIPLY', 'A {amount}-litre bottle is poured {n} times. How many litres?', {'a': v(12, 35), 'n': v(2, 6)}, {'amount': 'a/10', 'litres': 'a*n/10'}, '{litres}', 'Repeated equal amounts give n times the displayed bottle amount.', tags=['decimal_multiplication', 'units']),
    generated('ARITH009_DECIMAL_PRODUCT', 'Compute ({left})×({right}). Enter the decimal product.', {'a': v(2, 9), 'b': v(2, 9)}, {'left': 'a/10', 'right': 'b/10', 'product': 'a*b/100'}, '{product}', 'Tenths times tenths are hundredths; multiply the displayed decimal factors.', tags=['decimal_multiplication', 'place_value']),
    generated('ARITH009_SHARE', 'Share {total} litres equally among {n} containers. Litres per container?', {'a': v(12, 48), 'n': v(2, 8)}, {'total': 'a/10', 'each': 'a/(10*n)'}, '{each}', 'Divide the displayed total measure by the number of equal containers.', tags=['decimal_division', 'sharing']),
    generated('ARITH009_DIVISOR_TENTHS', 'How many {piece}-metre pieces fit in {total} metres?', {'d': v(2, 8), 'pieces': v(2, 12)}, {'piece': 'd/10', 'total': 'd*pieces/10'}, '{pieces}', 'The quotient counts full pieces of the displayed size; a fractional leftover is not counted.', tags=['decimal_division', 'full_pieces']),
    generated('ARITH009_TIMES_TEN', 'Compute {left}×10.', {'a': v(10, 99)}, {'left': 'a/100', 'answer': 'a/10'}, '{answer}', 'Multiplying the displayed hundredths value by 10 moves it to tenths.', tags=['powers_of_ten']),
    generated('ARITH009_DIVIDE_HUNDRED', 'Compute {left}÷100.', {'a': v(10, 99)}, {'left': 'a/10', 'answer': 'a/1000'}, '{answer}', 'Dividing the displayed tenths value by 100 shifts two places right.', tags=['powers_of_ten']),
    generated('ARITH009_SCALE_BOTH_TEN', 'Rewrite {left} ÷ {right} by scaling both entries by 10. Enter the quotient.', {'a': v(20, 90), 'b': v(2, 9)}, {'left':'a/10','right':'b/10','quotient': 'a/b'}, '{quotient}', 'Multiplying both dividend and divisor by 10 preserves their quotient.', tags=['quotient_scaling']),
    choice('ARITH009_SCALE_BOTH_HUNDRED', 'Which rewrite preserves 3.6÷0.12 while making the divisor a whole number?', 'C', [('A', '36÷0.12'), ('B', '3.6÷12'), ('C', '360÷12'), ('D', '360÷0.12')], 'Multiply both entries by 100: 360÷12 has the same quotient.', tags=['quotient_scaling', 'tool_choice']),
    choice('ARITH009_SCALE_WARNING', 'A learner writes 2.7 + 0.35 = 0.62 by aligning the last digits. What is the correction?', 'B', [('A','0.62 is correct'),('B','Align decimal points: 2.70 + 0.35 = 3.05'),('C','Count all digits and write 30.5'),('D','Addition always removes the decimal point')], 'Tenths must combine with tenths and hundredths with hundredths. Write 2.70 before adding.'),
    fixed('ARITH009_SCALE_RESULT', 'Calculate 2.5 + 0.4 × 3, following the order of operations.', '3.7', 'Multiply first: 0.4 × 3 = 1.2. Then 2.5 + 1.2 = 3.7.'),
    generated('ARITH009_ESTIMATE', 'A calculation is {left} + {right}. Round each addend to the nearest whole number first (halves round up), then add to estimate the sum.', {'a': v(10, 29), 'b': v(10, 29)}, {'left': 'a/10', 'right': 'b/10', 'exact': '(a+b)/10', 'estimate': '(a+5)//10+(b+5)//10'}, '{estimate}', 'Round each positive addend separately, with halves going up, then add the rounded values. This is an estimate, not the exact sum.', tags=['estimation', 'rounding']),
    choice('ARITH009_TRAILING_ZERO', 'Which statement correctly explains 2.50 = 2.5?', 'C', [('A','The zero changes hundredths into tens'),('B','All zeros can be deleted anywhere'),('C','50 hundredths equals 5 tenths'),('D','The values differ by 0.05')], 'A trailing zero contributes no extra hundredths. An interior or leading place-value zero cannot simply be removed.'),
    generated('ARITH009_MONEY_CHANGE', 'A customer pays {paid_decimal} dollars for an item costing {cost_decimal} dollars. Enter the change in dollars.', {'paid': v(500, 999), 'cost': v(100, 499)}, {'paid_decimal':'paid/100','cost_decimal':'cost/100','change': '(paid-cost)/100'}, '{change}', 'Subtract like money units and keep dollars attached to the decimal result.', tags=['decimal_subtraction', 'money']),
    fixed('ARITH009_UNIT_RATE', 'A length is 1.25 m plus 35 cm. Enter the total in metres.', '1.6', 'Convert 35 cm to 0.35 m, then add 1.25 + 0.35 = 1.60 m.'),
    choice('ARITH009_SCALE_MISSTEP', 'If only the dividend in a quotient is multiplied by 10, what happens to the quotient?', 'B', [('A', 'It stays unchanged'), ('B', 'It is multiplied by 10'), ('C', 'It is divided by 10'), ('D', 'It becomes undefined')], 'Scaling only the dividend changes the quotient; both entries must be scaled to preserve it.', tags=['quotient_scaling', 'misconception']),
    choice('ARITH009_UNIT_CHECK', 'Which decimal division is undefined?', 'A', [('A','3.5 ÷ 0'),('B','0 ÷ 3.5'),('C','3.5 ÷ 0.5'),('D','0.35 ÷ 0.1')], 'Zero cannot be a divisor: no number multiplied by zero reconstructs 3.5.'),
    choice('ARITH009_ORDER_MAGNITUDE', 'Which statement about 0.6×0.4 is true?', 'A', [('A', 'It is less than 0.6'), ('B', 'It equals 0.6'), ('C', 'It is greater than 0.6'), ('D', 'It is negative')], 'Multiplying a positive number by 0.4, between 0 and 1, makes it smaller.', tags=['magnitude', 'multiplication']),
    capstone('ARITH009_CAPSTONE', 'A lab has 3.6 litres and fills vials of 0.12 litres. Enter the number of full vials.', '30', ['Identifies division by the vial size and states the quotient as a count of vials.', 'Scales both 3.6 and 0.12 by 100, showing 360÷12 without changing the quotient.', 'Checks 30×0.12=3.6 and explains why scaling only one entry would change the problem.'], '3.6÷0.12=(3.6×100)/(0.12×100)=360÷12=30 full vials.'),
]

figure('arith009-place-value.svg', 'Decimal place-value shifts', '<text x="38" y="110" font-size="28">3.47</text><path d="M140 102 H285" stroke="#287365" stroke-width="4"/><text x="310" y="110" font-size="28">347</text><text x="38" y="160" font-size="19">×100: digits shift two place-value columns left</text><text x="38" y="235" font-size="28">4.2</text><path d="M140 227 H285" stroke="#287365" stroke-width="4"/><text x="310" y="235" font-size="28">0.042</text><text x="38" y="285" font-size="19">÷100: digits shift two place-value columns right</text>')
figure('arith009-quotient-scaling.svg', 'Scale both entries of a quotient', '<rect x="48" y="88" width="260" height="92" fill="#d9eee5"/><rect x="492" y="88" width="260" height="92" fill="#f5dfb5"/><text x="178" y="143" text-anchor="middle" font-size="27">3.6 ÷ 0.12</text><text x="400" y="143" text-anchor="middle" font-size="28">×100</text><text x="622" y="143" text-anchor="middle" font-size="27">360 ÷ 12</text><text x="268" y="238" font-size="23">same quotient = 30</text>')

save('MATH_ARITH_009', 'Decimal operations, powers of ten and quotient scaling', theory, ['MATH_ARITH_005', 'MATH_ARITH_006'], examples, apps, questions, [media('arith009-place-value.svg', 'Two decimal examples show multiplication by 100 shifting digits left and division by 100 shifting right with zero placeholders.', 'Powers of ten change place value by a precise number of places.'), media('arith009-quotient-scaling.svg', 'A quotient 3.6 divided by 0.12 is rewritten as 360 divided by 12 after multiplying both entries by 100.', 'A common nonzero scale factor preserves a quotient only when applied to both entries.')], tags=['arithmetic', 'decimals', 'operations', 'powers_of_ten', 'quotient_scaling'])
