"""Build the lesson-by-lesson reference from the actual shipped catalog."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"


def read(path):
    return json.loads(path.read_text(encoding="utf-8"))


def build():
    taxonomy = read(DOCS / "learning-taxonomy.json")
    lessons = [("SUBJECT_MATH", skill) for skill in read(DOCS / "curriculum-data.json")["skills"]]
    latest = {}
    for path in (DOCS / "lesson-depot/lessons").glob("**/lesson-set.json"):
        pack = read(path)
        version = tuple(int(part) for part in pack["version"].split("."))
        if pack["id"] not in latest or version > latest[pack["id"]][0]:
            latest[pack["id"]] = (version, pack)
    for _, pack in latest.values():
        lessons.extend((pack["subject"]["id"], skill) for skill in pack["skills"])
    lines = ["# Fields and branches", "", f"The shipped library contains {len(lessons)} lessons. Field IDs and lesson IDs are unchanged. `subdomain` stores the broad branch; optional `topic` preserves the previous focused category.", "", "Canonical maps group lessons inside branch bands within each field. Existing saved coordinates remain in Plan view; **Plan mode → Plan details → Group by field & branch** adopts the canonical positions while retaining notes and paths.", ""]
    for field in taxonomy["fields"]:
        lines += [f"## {field['name']}", ""]
        for branch in field["branches"]:
            members = [skill for field_id, skill in lessons if field_id == field["id"] and skill["subdomain"] == branch]
            lines += [f"### {branch} ({len(members)} lessons)", "", "| Lesson | Topic | Stable lesson ID |", "| --- | --- | --- |"]
            for skill in members:
                lines.append(f"| {skill['name']} | {skill.get('topic') or '-'} | `{skill['id']}` |")
            lines += [""]
    lines += ["## Compatibility", "", "Known legacy categories are converted when lesson sets, curricula, backups and Studio drafts load. The original category becomes the topic. Unknown custom branches are kept. Reuse the broad branches above for new lessons and reserve topics for smaller teaching units. New fields and branches remain supported.", "", "The machine-readable source, including legacy aliases, is [learning-taxonomy.json](./learning-taxonomy.json). This reference is generated by `scripts/build_branch_reference.py`.", ""]
    (DOCS / "FIELDS_AND_BRANCHES.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    build()
