"""Build MATH_ARITH_011: ratios, unit rates and proportional sharing."""
from native_number_foundations_common import *

theory = '''A ratio compares quantities by division or by a colon notation such as 3:5. The order matters: 3 red beads to 5 blue beads is not the same statement as 5 red to 3 blue. A ratio can compare parts of one collection or two different units, but label the quantities so the comparison is interpretable. The ratio 3:5 means that for every 3 units of the first quantity there are 5 units of the second; it does not by itself say the collection has only 8 units.

Equivalent ratios multiply or divide both parts by the same nonzero factor. 3:5, 6:10, and 15:25 describe the same relationship. To simplify 18:30, divide both entries by their GCF, 6, giving 3:5. Dividing only one side destroys equivalence. A ratio table keeps the paired values in columns, while a double number line places corresponding values at the same scaled positions. Both representations make the “same multiplier” visible and help detect a reversed or uneven scaling.

A unit rate is a rate for one unit of the reference quantity. If 240 km takes 4 hours, the unit rate is 240÷4 = 60 km per hour. The denominator tells what “per one” means. Cost per item, litres per minute, and pages per day are all unit rates; swapping numerator and denominator changes the question. A rate can be used forward by multiplying by the number of reference units, or backward by dividing a total by the unit rate. Carry units through every step so that 60 km/h is not mistaken for 60 hours/km.

Proportional situations have a constant ratio or constant unit rate. If 3 notebooks cost $6, then 1 notebook costs $2 and 8 notebooks cost $16, assuming the same price rule. The relationship can be represented by a table, a double number line, an equation y=kx, or a graph through the origin. A fixed delivery fee breaks direct proportionality: two items may cost more than twice the cost of one if the fee is charged once. Check the context before extending a ratio.

To share a total in a ratio, add the ratio parts to find the number of equal shares. For 3:5 and a total of 64, there are 8 parts, so one part is 64÷8=8. The first amount is 3×8=24 and the second is 5×8=40. Check 24+40=64 and 24:40 simplifies back to 3:5. This is different from taking 3/5 of the total: the first share is 3/(3+5) of the total because the total includes both groups.

Percent, fraction, and ratio language can connect, but do not silently switch reference bases. A ratio of 1:4 means 1 out of 5 total parts if the two parts exhaust a whole, which is 20%, not 25%. A ratio of boys to girls 1:4 does not mean boys are 25% of all pupils unless those are the only two groups; it means one boy for every four girls. State whether a fraction is part-to-whole or part-to-part.

Scale drawings and maps use ratios with units that may differ. A map scale 1 cm:5 km means 3 cm represents 15 km. Convert units before comparing rates, and use a proportion with matched columns. A good table repeats the same multiplier down both columns. If one known pair is 4 tickets for $18, then 10 tickets at the same unit price cost $45; if the context has bulk discounts, that inference needs qualification.

Read ratio questions in order: name the two quantities, decide whether the comparison is part-to-part or a rate, simplify or scale both entries, and verify units and totals. The capstone asks you to share a fixed total fairly according to a ratio and justify the part-to-whole calculation.
A ratio table is a claim about correspondence, not merely a convenient arrangement of numbers. If 4 tickets cost 18 dollars and the relationship is proportional, every row has cost/tickets=4.50 dollars per ticket. A row such as 10 tickets for 40 dollars would signal a changed price rule, a discount, or an error. State which assumption you are using before extrapolating.

Rates can be converted without changing the underlying relationship. For 60 km/h, multiplying numerator and denominator by 1000 and 3600 gives 1,000 m/3,600 s, or 16 2/3 m/s. The number changes because the reference units change, but the physical motion is the same. In a share, the ratio parts are dimensionless counts; the total carries dollars, grams, or people, so the value of one part inherits the total unit. These distinctions keep ratio arithmetic connected to the situation.
'''

examples = [
    example('Simplify 18:30.', '3:5', 'Divide both terms by their GCF, 6.'),
    example('Give two ratios equivalent to 3:5.', '6:10 and 15:25', 'Multiply both terms by 2 and by 5.'),
    example('240 km takes 4 hours. Find km per hour.', '60 km/h', 'Divide distance by time; the denominator is one hour.'),
    example('Three notebooks cost $6. At the same rate, what do 8 cost?', '$16', 'The unit price is $2, then 8×$2=$16.'),
    example('Share 64 in the ratio 3:5.', '24 and 40', 'There are 8 total parts; each is 8.'),
    example('What does 3:5 mean in words?', 'Three of the first for every five of the second.', 'Ratios preserve order and compare corresponding quantities.'),
    example('A map scale is 1 cm:5 km. What distance is 3 cm?', '15 km', 'Multiply both scale entries by 3.'),
    example('Why is a fixed delivery fee not directly proportional to item count?', 'The total does not double when the item count doubles.', 'The additive fee changes the ratio total/items.'),
    example('If 1 out of 4 girls is the ratio boys:girls, what fraction of all two-group pupils are boys?', '1/5', 'One boy plus four girls makes five total parts.'),
    example('A machine makes 18 parts in 6 minutes. Find its unit rate.', '3 parts/minute', 'Divide output by minutes; 18÷6=3.'),
]
apps = [
    application('Recipes and mixtures', 'Ingredient ratios scale a batch while keeping the same flavour or concentration.'),
    application('Travel and maps', 'Unit rates convert distance and time, and scale ratios turn map measurements into real distances.'),
    application('Budgets and wages', 'Prices per item and pay per hour support comparisons and forecasts with explicit reference units.'),
    application('Fair sharing', 'A ratio allocates a total into proportional shares while a part-to-whole check verifies that nothing is lost.'),
]
v = lambda lo, hi: {"type": "int", "min": lo, "max": hi}
questions = [
    generated('ARITH011_EQUIV_RATIO', 'A recipe uses 3 cups flour for every 2 cups water. If water is {water} cups, how much flour is needed?', {'k': v(2, 8)}, {'water': '2*k', 'flour': '3*k'}, '{flour}', 'The same ratio multiplies both recipe amounts by k; flour is 3 parts when water is 2 parts.', tags=['equivalent_ratios', 'recipe']),
    fixed('ARITH011_RATIO_SECOND', 'Two quantities are in ratio 4:7 and differ by 21. Enter the larger quantity.', '49', 'The ratio difference is 3 parts, so one part is 7 and the larger quantity is 7×7=49.', tags=['ratio_from_difference']),
    fixed('ARITH011_SIMPLIFY', 'Simplify 18:30 by entering the first term of the simplest ratio.', '3', 'Divide 18 and 30 by 6 to obtain 3:5.', tags=['simplify_ratio']),
    fixed('ARITH011_UNIT_RATE', 'Convert 72 km/h to metres per second.', '20', '72×1000÷3600=20 m/s; both distance and time units are converted.', tags=['unit_conversion', 'rate']),
    generated('ARITH011_RATE_FORWARD', 'A printer makes {rate} pages per minute for {minutes} minutes. Total pages?', {'rate': v(3, 9), 'minutes': v(4, 12)}, {'pages': 'rate*minutes'}, '{pages}', 'Multiply the unit rate by the number of minutes.', tags=['unit_rate', 'proportion']),
    generated('ARITH011_RATE_BACK', 'A printer makes {pages} pages in {minutes} minutes. Pages per minute?', {'minutes': v(3, 8), 'rate': v(3, 9)}, {'pages': 'rate*minutes', 'unit': 'rate'}, '{unit}', 'Divide total pages by minutes to recover the constant unit rate.', tags=['unit_rate']),
    fixed('ARITH011_PARTS_TOTAL', 'In ratio 3:5, enter the number of total parts.', '8', 'Add the ratio terms: 3+5=8 equal parts.', tags=['ratio_sharing']),
    choice('ARITH011_SHARE_FIRST', 'A learner shares 100 in ratio 2:3:5 as 20, 30, and 50. Which explanation is correct?', 'A', [('A', 'There are 10 parts, so one part is 10'), ('B', 'The ratio terms should be multiplied by 100 directly'), ('C', 'The largest share must equal the total'), ('D', 'The three shares should be equal')], 'Adding 2+3+5 gives 10 parts; 100÷10=10 per part, producing 20, 30, and 50.', tags=['ratio_sharing', 'error_analysis']),
    fixed('ARITH011_SHARE_SECOND', 'Share 90 in ratio 2:3. Enter the second share.', '54', 'There are 5 parts, so one part is 18 and the second share is 3×18=54.', tags=['ratio_sharing']),
    generated('ARITH011_SHARE_VARIABLE', 'A total of {total} is shared in ratio 2:3. Enter the first share.', {'k': v(4, 15)}, {'total': '5*k', 'share': '2*k'}, '{share}', 'The total has 5 ratio parts; one part is k and the first share has 2 parts.', tags=['ratio_sharing', 'proportional_sharing']),
    fixed('ARITH011_MAP', 'A map scale is 1 cm:5 km. How many centimetres represent 7 km?', '1.4', 'Divide 7 km by 5 km per centimetre: 1.4 cm.', tags=['scale_drawing', 'double_number_line']),
    generated('ARITH011_MAP_VARIABLE', 'A map uses 1 cm:{km} km. Enter kilometres represented by {cm} cm.', {'km': v(2, 8), 'cm': v(2, 6)}, {'distance': 'km*cm'}, '{distance}', 'Multiply the kilometres per centimetre by the number of centimetres.', tags=['scale_drawing']),
    choice('ARITH011_PART_WHOLE', 'If boys:girls=1:4 and these are the only groups, which fraction represents boys of the whole?', 'A', [('A', '1/5'), ('B', '1/4'), ('C', '4/5'), ('D', '4/1')], 'There are 1+4=5 total parts, so boys are one fifth of the whole.', tags=['part_to_whole']),
    choice('ARITH011_RATE_UNITS', 'Which rate is faster?', 'A', [('A', '3 m in 2 s'), ('B', '120 cm in 1 s'), ('C', 'They are equal'), ('D', 'The units cannot be compared')], '3 m in 2 s is 1.5 m/s, while 120 cm in 1 s is 1.2 m/s.', tags=['rate_comparison', 'mixed_units']),
    generated('ARITH011_COST', '{count} notebooks cost {unit} dollars each. Enter total cost.', {'count': v(3, 9), 'unit': v(2, 7)}, {'cost': 'count*unit'}, '{cost}', 'At a constant unit price, total cost is count×price.', tags=['proportion', 'money']),
    choice('ARITH011_DENOMINATOR', 'In 60 km/h, what does the denominator h mean?', 'B', [('A', 'Per 60 hours'), ('B', 'Per one hour'), ('C', 'A distance unit'), ('D', 'A total count')], 'The denominator identifies the reference unit: 60 kilometres for each one hour.', tags=['unit_rate', 'meaning']),
    choice('ARITH011_FIXED_FEE', 'A shop charges 5 dollars per item plus a fixed 3 dollar fee. Is total cost directly proportional to item count?', 'B', [('A', 'Yes, every item costs 5 dollars'), ('B', 'No, the fixed 3 dollars does not scale with item count'), ('C', 'Yes, because 3 dollars is a ratio'), ('D', 'Only when the item count is zero')], 'The additive 3 dollar fee means doubling item count does not double the total.', tags=['proportionality']),
    generated('ARITH011_RATIO_CHECK', 'A double number line aligns 4 red beads with 10 blue beads. At {blue} blue beads, how many red beads correspond?', {'k': v(2, 6)}, {'blue': '10*k', 'red': '4*k'}, '{red}', 'The same scale factor k applies down both number lines: 4k red matches 10k blue.', tags=['double_number_line', 'equivalent_ratios']),
    choice('ARITH011_REVERSE_WARNING', 'Which statement about 3:5 and 5:3 is correct?', 'C', [('A', 'They always mean the same ordered comparison'), ('B', 'They are both simplified to 1:1'), ('C', 'Reversing terms changes the ordered comparison'), ('D', 'Ratios have no order')], 'The first and second quantities swap roles when the terms reverse.', tags=['ratio_order']),
    capstone('ARITH011_CAPSTONE', 'A community fund of $64 is shared between two teams in ratio 3:5. Enter the first team’s dollars.', '24', ['Adds ratio parts to obtain 8 equal parts and divides $64 by 8.', 'Multiplies the first ratio term by the value of one part to obtain $24.', 'Checks that the second share is $40, the total is $64, and 24:40 simplifies to 3:5 with units stated.'], 'There are 8 parts, so one part is $8. The first team receives 3×$8=$24 and the second $40; 24+40=$64 and 24:40=3:5.'),
]

figure('arith011-ratio-table.svg', 'Equivalent ratios keep one multiplier', '<rect x="70" y="82" width="260" height="62" fill="#d9eee5"/><rect x="470" y="82" width="260" height="62" fill="#d9eee5"/><text x="200" y="122" text-anchor="middle" font-size="26">3 red</text><text x="600" y="122" text-anchor="middle" font-size="26">5 blue</text><path d="M200 150 V216" stroke="#287365" stroke-width="4"/><path d="M600 150 V216" stroke="#287365" stroke-width="4"/><text x="216" y="190" font-size="18">×2</text><text x="616" y="190" font-size="18">×2</text><rect x="70" y="224" width="260" height="62" fill="#f5dfb5"/><rect x="470" y="224" width="260" height="62" fill="#f5dfb5"/><text x="200" y="264" text-anchor="middle" font-size="26">6 red</text><text x="600" y="264" text-anchor="middle" font-size="26">10 blue</text>')
figure('arith011-sharing.svg', 'Share 64 in ratio 3:5', '<rect x="58" y="96" width="300" height="82" fill="#d9eee5"/><rect x="438" y="96" width="300" height="82" fill="#f5dfb5"/><text x="208" y="147" text-anchor="middle" font-size="27">3 parts × $8 = $24</text><text x="588" y="147" text-anchor="middle" font-size="27">5 parts × $8 = $40</text><text x="175" y="250" font-size="22">3 + 5 = 8 parts; 64 ÷ 8 = $8 each</text>')

save('MATH_ARITH_011', 'Ratios, unit rates and proportional sharing', theory, ['MATH_ARITH_004', 'MATH_ARITH_009'], examples, apps, questions, [media('arith011-ratio-table.svg', 'A ratio table scales 3 red and 5 blue by the same factor 2 to 6 red and 10 blue.', 'Both columns must receive the same multiplier.'), media('arith011-sharing.svg', 'A 64 dollar total is partitioned into 3 parts of 8 dollars and 5 parts of 8 dollars.', 'Sharing starts by finding the value of one ratio part.')], tags=['arithmetic', 'ratios', 'unit_rates', 'proportionality', 'sharing'])
