"""Teaching captions, kept separate from labels used inside the figures."""
CAPTIONS = {
    "fraction-division": "Division asks how many groups of the divisor fit into the dividend. Two thirds contains four groups of one sixth, so 2/3 ÷ 1/6 = 4.",
    "interval-union": "OR takes the union of two regions. Include −2, exclude 3, and continue outward indefinitely; infinity never receives a closed bracket.",
    "function-mapping": "Both −2 and 2 map to 4 under squaring. This is a function because each input still has exactly one output.",
    "shifted-log-domain": "The argument x − 3 must be positive. Shifting log₂(x) right by 3 moves its domain to x > 3 and its vertical asymptote to x = 3.",
    "system-cases": "Two straight lines either intersect once, remain parallel and distinct, or coincide. These correspond to one, zero and infinitely many simultaneous solutions.",
    "binary-search": "Binary search requires sorted input. Each highlighted midpoint comparison discards half the remaining candidates until the target 13 is found.",
    "MATH_ARITH_001": "Start at −6 and move four units left. Adding −4 gives −10.",
    "MATH_ARITH_002": "Evaluate the multiplication first, then add: 7 + 3 × 4 = 7 + 12 = 19.",
    "MATH_ARITH_003": "Both strips use eighths. Three shaded parts represent 3/8; four shaded parts represent 4/8, which is one half.",
    "MATH_ARITH_004": "Two of three columns cover 2/3 of the whole. Taking three quarters of that region shades six of twelve equal cells: 1/2.",
    "MATH_ARITH_005": "A percent grid has 100 equal cells. Shading 35 cells connects the fraction 35/100, the decimal 0.35 and 35%.",
    "MATH_PREALG_001": "Replace x with −3 everywhere it occurs, keeping the negative value in parentheses before calculating.",
    "MATH_PREALG_002": "Each tile stands for the same quantity x. Three x tiles and two x tiles combine to make five x tiles.",
    "MATH_PREALG_003": "Split the rectangle into widths x and 2 with shared height 3. Its two areas add to 3x + 6.",
    "MATH_PREALG_004": "Distribute before grouping like terms. Only terms with the same variable part combine.",
    "MATH_PREALG_005": "Three packs of x items contribute 3x items. Two separate extras are then added to form 3x + 2.",
    "MATH_ALG_001": "An equation stays balanced when the same quantity is removed from both sides. Here, subtracting 3 leaves x = 4.",
    "MATH_ALG_002": "Undo addition before multiplication: subtract 3 from both sides, then divide both sides by 2.",
    "MATH_ALG_003": "Collect variable terms on one side and constants on the other, performing each operation on both sides.",
    "MATH_ALG_004": "Parallel, distinct lines never meet, so their equations cannot both hold at one point. Identical lines instead share every point.",
    "MATH_ALG_005": "The area relationship A = wh can be solved for width by dividing by the nonzero height: w = A/h.",
    "MATH_ALG_006": "A filled endpoint includes −2; an open endpoint excludes 5. The highlighted interval is [−2, 5).",
    "MATH_ALG_007": "Negation reflects positions across zero and reverses their order. If x is less than 2, then −x is greater than −2.",
    "MATH_ALG_008": "Both −7 and 7 are seven units from zero. Absolute value measures that distance, regardless of direction.",
    "MATH_INEQ_001": "Interval notation records both the shaded values and the endpoints: [ includes −2, while ) excludes 5.",
    "MATH_INEQ_002": "The product (x − 2)(x − 5) is positive outside its two zeros and negative between them. Decide whether to include the zeros from the inequality sign.",
    "MATH_FUNC_001": "Follow one input through a function rule. A function assigns one output to each input; different inputs are allowed to share an output.",
    "MATH_SYS_001": "The intersection (3, 7) satisfies both equations simultaneously. This is the common solution to the system.",
    "MATH_SEQ_001": "An arithmetic sequence adds a fixed difference. The discrete points increase by 3 per term; dashed segments guide the eye.",
    "MATH_SEQ_002": "A geometric sequence multiplies by a fixed ratio. Doubling each term creates increasing gaps; dashed segments guide the eye.",
    "MATH_POLY_001": "Like terms share the same powers of the same variables. Group x terms together, keeping x² terms and constants separate.",
    "MATH_POLY_002": "The four subrectangles show every pair of factors in (x + 2)(x + 3). Their areas sum to x² + 5x + 6.",
    "MATH_POLY_003": "Factoring reverses distribution: the shared height 3x turns 3x² + 6x into 3x(x + 2).",
    "MATH_POLY_004": "Read the rectangle in reverse to factor x² + 5x + 6. The two side extensions are 2 and 3: their sum is 5 and their product is 6.",
    "MATH_QUAD_001": "The graph of (x − 2)(x − 5) crosses the x-axis at 2 and 5, where one of its factors is zero.",
    "MATH_QUAD_002": "Completing the square adds the missing corner. The two 3x strips need a 3-by-3 square to form (x + 3)².",
    "MATH_QUAD_003": "Compare x² − 2, x² and x² + 2. A positive, zero or negative discriminant corresponds to two, one or no real x-intercepts.",
    "MATH_QUAD_004": "Vertex form makes the turning point (2, −3) and symmetry line x = 2 visible. The factor 2 changes the vertical scale.",
    "MATH_QUAD_005": "With perimeter 40, the other side is 20 − x. The area x(20 − x) reaches its maximum at a 10-by-10 square; physical widths lie between 0 and 20.",
    "MATH_EXP_001": "Multiplying powers with the same base joins their factors. Two copies of a and three copies of a make five copies in total.",
    "MATH_EXP_002": "A base greater than 1 produces growth; a base between 0 and 1 produces decay. Both plotted quantities stay positive.",
    "MATH_EXP_003": "The intersection of y = 2ˣ and y = 16 locates the solution. The dotted guide connects it to the x-axis.",
    "MATH_LOG_001": "Exponential and logarithmic inverses reflect across y = x. For base 2, the exponential's horizontal asymptote corresponds to the logarithm's vertical asymptote.",
    "MATH_LOG_002": "Equal steps on a base-10 logarithmic scale correspond to multiplying the original quantity by 10.",
    "MATH_LOG_003": "To solve 3 × 2ˣ = 20, locate the intersection with y = 20. Logarithms find the x-value even when it is not an integer.",
    "MATH_RAD_001": "Split 72 into 36 × 2. The complete square contributes 6 outside the radical, leaving 6√2.",
    "MATH_RAT_001": "Denominators restrict the original domain. Cancelling x − 2 leaves a hole at x = 2; the uncancelled factor x − 4 creates a vertical asymptote.",
    "MATH_RAT_002": "Cancel a common factor only on the original allowed domain. The simplified expression x + 3 still excludes x = 2.",
    "MATH_RAT_003": "Rewrite both fractions with the same denominator before adding their numerators. The denominator describes the size of each part.",
    "MATH_RAT_004": "Multiplying by the common denominator simplifies the equation, but x = 0 remains excluded throughout. Check the candidate in the original equation.",
    "MATH_RAT_005": "Clearing denominators can produce a forbidden candidate. Here x = 1 makes the original denominators zero, so it must be rejected.",
    "MATH_RAT_006": "An open circle marks the removable hole at (2, −1.5). The dashed lines mark x = 4 and y = 1, the vertical and horizontal asymptotes.",
    "MATH_RAT_007": "The rational expression changes sign at 2 and 5. The numerator is zero at 2, but 5 is excluded because it makes the denominator zero.",
    "CUSTOM_ESTIMATION_SANITY": "Rounding 47 × 19 up to 50 × 20 gives 1000. The exact result 893 should be nearby and smaller. Rectangles are schematic.",
    "special-triangles": "The side ratios are 1:1:√2 and 1:√3:2. Scale all three sides together to build any similar special right triangle.",
    "elevation": "A vertical height and horizontal distance form perpendicular legs. Their ratio h/d is the tangent of the angle of elevation.",
    "radian-arc": "A radian measures arc length relative to radius. With r = 6 and θ = π/3, the corresponding arc has length 2π.",
    "reference-turns": "225° and −135° end on the same ray. The reference angle is the acute gap to the x-axis: 45°.",
    "period-phase": "Compare one change at a time: sin(2x) halves the period, while sin(x − π/4) shifts the original wave right by π/4.",
    "quadrant-signs": "At (−12, 5), the radius is 13. The horizontal component makes cosine negative, while the vertical component makes sine positive.",
    "restricted-cycles": "Doubling the input gives two full cosine cycles on [0, 2π). Check every x-intercept in the allowed interval to find all four roots.",
    "tangent": "Tangent has separate branches divided by vertical asymptotes. Its intersections with y = −1 occur at 3π/4 and 7π/4 on this interval.",
    "ssa": "For A = 30° and b = 8, the altitude is 4. A circle of radius a intersects the base ray zero, one or two times as a changes from 3 to 4 to 5.",
    "included-area": "Drop a perpendicular altitude to the chosen base. Since h = a sin(C), the area becomes ½ab sin(C) for the included angle C.",
    "recursion-stack": "Recursive calls descend to the base case, then return in reverse order. Each suspended call finishes its multiplication as the stack unwinds.",
    "memoization": "A dependency sketch shows where fib(3) is shared. Memoization stores its result so a later request reuses it instead of repeating the subtree.",
}
PYTHON = [
    "Follow a small algorithm from input to output. Each step has a clear job and an observable effect.",
    "Names refer to values. An integer 7 and the string \"7\" may print alike, but support different operations.",
    "Input arrives as text. Convert it to an integer before arithmetic, then print the result.",
    "Read each truth-table row independently. AND needs both inputs true; OR needs at least one.",
    "Evaluate the condition once and follow exactly one branch: score ≥ 60 passes, otherwise it fails.",
    "A while loop tests its condition before each iteration. Incrementing n from 0 eventually makes n < 4 false.",
    "The accumulator starts at zero and remembers the running total after each value is added.",
    "Arguments become local parameters for this call. A return value carries the result back to the caller.",
    "Positive and negative indices address the same characters. The slice [1:3] includes index 1 and stops before index 3.",
    "items and alias point to one list, so alias.append(3) affects both names. An earlier shallow copy keeps its own list of these immutable numbers.",
    "Filtering decides which items survive; mapping transforms each surviving item. These are separate steps.",
    "Dictionary keys identify associated values. Looking up counts[\"red\"] retrieves its count without a positional index.",
    "Test empty, typical and invalid inputs. A reproducible failing case helps isolate the behavior that needs fixing.",
    "Divide a program by responsibility. Explicit inputs and outputs make each small function easier to test.",
    "Validation sits between reading data and calculating a summary. Test the boundaries of each stage.",
    "A tuple preserves positions and cannot have its items reassigned. A set stores unique members and has no positional indexing.",
    "Follow keys and indices through a nested record. The scores list holds separate values at positions 0 and 1.",
    "A with statement manages the file's lifetime. Leaving its body closes the file, including when an exception occurs.",
    "A matching handler receives an exception; else runs on success. finally provides cleanup on both paths.",
    "A caller imports a module's definitions and accesses them through names. The module provides a reusable boundary.",
    "A comprehension filters candidate inputs before evaluating its output expression. Here, odd inputs are squared.",
    "Two Counter instances have separate instance state. Incrementing the first does not change the second.",
    "Compare logarithmic, linear and quadratic growth in work. These are operation-count models, not hardware timing predictions.",
    "Keep argument parsing, domain calculations and persistence in separate components so calculations can be tested independently.",
    "The in-memory state can differ from the saved file. Validate changes before writing a new persistent version.",
    "A dataclass can validate invariants in __post_init__. Type annotations alone do not enforce the allowed range of values.",
    "A generator preserves its state at yield and resumes on the next request. Exhaustion ends the sequence with StopIteration.",
    "Preorder traversal visits a node before its children, finishing one subtree before moving to the next.",
]
CAPTIONS.update({f"CUSTOM_PROG_{i:03}": value for i,value in enumerate(PYTHON,1)})
CAPTIONS.update({
    "GEO_FOUND_001": "Nested scales connect a site to its neighborhood, city and region. The relevant explanation can change when the geographic scale changes.",
    "GEO_CART_001": "Mercator increases spacing between parallels toward the poles. The comparison illustrates distortion, not a navigational map.",
    "GEO_CART_002": "Parallels measure latitude north or south of the equator; meridians measure longitude east or west of the prime meridian. The globe is schematic.",
    "GEO_GIS_001": "A GIS aligns roads, rivers and land use to shared locations, allowing evidence from different layers to be combined.",
    "GEO_PHYS_001": "In this idealized convergent margin, an oceanic plate descends beneath another plate. The cross-section links compression, a trench and a volcanic arc.",
    "GEO_PHYS_002": "In the idealized three-cell model, surface air flows toward equatorial and subpolar low-pressure belts. Real winds are also deflected by Earth's rotation.",
    "GEO_PHYS_003": "The drainage divide encloses tributaries that feed a common outlet. Water on the other side of the divide drains elsewhere.",
    "GEO_PHYS_004": "Temperature and moisture constrain broad biome patterns. These boxes are conceptual categories, not measured boundaries or a complete biome classification.",
    "GEO_HUMAN_001": "Compare the relative widths of younger and older age groups. These are illustrative population shapes, not demographic data for actual countries.",
    "GEO_HUMAN_002": "Migration connects an origin and destination through a route. Push factors, pull factors, barriers and networks all influence movement.",
    "GEO_URBAN_001": "Transport corridors and accessibility influence urban land use. The concentric layout is a conceptual model; real cities have less regular patterns.",
    "GEO_ECON_001": "Production links raw materials, components, assembly and markets across places. Value, jobs and environmental effects differ between stages.",
    "GEO_POL_001": "A cultural region can cross a state border. The schematic distinguishes political territory from cultural identity without depicting an actual territorial claim.",
    "GEO_RISK_001": "A hazard's consequences depend on who and what is exposed and how vulnerable they are. Preparedness and recovery capacity can reduce losses.",
    "GEO_SYNTH_001": "A regional explanation connects physical conditions with settlement, infrastructure, economic activity and risk instead of treating each layer in isolation.",
})
